### ISSUE TITLE
5 深度 > 癌症 > 15敏感性与特异性进一步介绍 > 链接

### ISSUE THREAD

**Issue by casper5300** [udacity/aipnd-issues-zh#169]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/54e18898-2666-445d-ba5c-ecab62a61d00/concepts/c225888e-8e82-4020-a641-acdda4008fa5

## 截图
![_20180411230958](https://user-images.githubusercontent.com/26052156/38626387-09e28f78-3ddf-11e8-84c4-add806b9091b.png)
![_20180411230938](https://user-images.githubusercontent.com/26052156/38626389-0ae7528c-3ddf-11e8-9b9c-295393bc8c44.png)

## 具体描述
链接打不开

**Comment by UdacityShuwenLiu** [comment]
这个链接link到深度学习的课程，所以学员没有权限打开，已经将这句话删去，不影响学员理解知识点。
