### ISSUE TITLE
深度学习 > 课程4 癌症检测深度学习 > 24 混淆矩阵回顾

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#260]
## 课程导航+地址
深度学习 > 课程4 癌症检测深度学习 > 24 混淆矩阵回顾
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/54e18898-2666-445d-ba5c-ecab62a61d00/concepts/30493758-5ce5-4239-b206-309997c61932

## 截图

<img width="764" alt="default" src="https://user-images.githubusercontent.com/34020359/39368452-2c0d7b0a-4a6c-11e8-9403-1c88331b34d4.png">

## 具体描述
该视频没有权限打开
你目前无法访问此纳米学位的内容。可能你的订阅已过期。

**Comment by UdacityShuwenLiu** [comment]
已修复
