### ISSUE TITLE
监督学习> 课程四 朴素贝叶斯> 资料包

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#262]
## 课程导航+地址
例子：进阶 > 经典街机游戏克隆 > 编写readme文档 > [1. 欢迎](教室地址链接)

## 截图
![image](https://user-images.githubusercontent.com/34020359/39396954-ede4a40c-4b29-11e8-9d03-c93b8c49eeb2.png)

## 具体描述
缺少字幕资料包

**Comment by UdacityShuwenLiu** [comment]
已修复
