### ISSUE TITLE
监督学习 > 第五课 支持向量机 > 资料包

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#263]
## 课程导航+地址
监督学习 > 第五课 支持向量机 > 资料包
## 截图
![image](https://user-images.githubusercontent.com/34020359/39396970-1e752fa6-4b2a-11e8-9a39-2b3a683f532b.png)

## 具体描述
缺少字幕资料包

**Comment by UdacityShuwenLiu** [comment]
已修复
