### ISSUE TITLE
神经网络 > 神经网络简介 > 2 分类问题 > 提交答案后视频无法显示

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#269]
## 课程导航+地址
神经网络 > 神经网络简介 > [2. 分类问题](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/501ce6c5-9b80-4536-8754-f7da607fc40d)
## 截图

![2018-05-03 1](https://user-images.githubusercontent.com/18286481/39579894-6cf7acfa-4f1a-11e8-85b0-2990501a974f.png)
![2018-05-03](https://user-images.githubusercontent.com/18286481/39580252-4c710728-4f1b-11e8-8345-c6bf0d25e69d.png)

## 具体描述
下方quiz完成后点击提交，如果正确的话，跳出截图上的框，可以看到里面有个视频，但是视频无法正确显示（截图1），0.5秒之后视频框消失（截图2）。

**Comment by UdacityShuwenLiu** [comment]
因为这个视频是 youtube 视频，暂时无法搬运至国内，已经在下方用文字提醒学生了。非常感谢提醒！：P
