### ISSUE TITLE
神经网络 > 神经网络简介 > 9. 感知器技巧 > 文字内容无法理解

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#270]
## 课程导航+地址
神经网络 > 神经网络简介 > [9. 感知器技巧](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/8ea20904-0215-4e44-afa9-bb5a720bd028)

## 具体描述
原文：**理论原理**是我们向它们提供结果，它们自己进行构建。
上方加粗字，理论原理在此处使句子不通顺，整句句子很难理解。其次，句中的**结果**，用**标签**更加恰当。

**Comment by nicoleliu42** [comment]
感谢反馈！已修改！这里的“结果”原文就是“result”，未作修改！
