### ISSUE TITLE
神经网络 > 神经网络简介 > 10. 感知器算法 > 文字内容错误

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#271]
## 课程导航+地址
神经网络 > 神经网络简介 > [10. 感知器算法](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/dc837952-c0d8-43fc-921c-f1ffe316c795) 

## 截图
![image](https://user-images.githubusercontent.com/18286481/39583570-f82693c4-4f22-11e8-8608-91d7bf374f14.png)

## 具体描述
位置：首行
原文：掌握了感知器技巧后，我们就可以**指定**完整的感知器算法了！
加粗字**指定**，在此处应替换为 **制定**，或其他更好的词。

**Comment by nicoleliu42** [comment]
感谢反馈！这里我改成了“编写”~
