### ISSUE TITLE
神经网络 > 神经网络简介 > 10. 感知器算法 > 测试答案效果与描述不符

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#272]
## 课程导航
神经网络 > 神经网络简介 > [10. 感知器算法](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/dc837952-c0d8-43fc-921c-f1ffe316c795)

##### 截图1
![image](https://user-images.githubusercontent.com/18286481/39584951-3764c18e-4f26-11e8-80d5-b6ae53cf69d5.png)
##### 截图2
![image](https://user-images.githubusercontent.com/18286481/39584994-51d977f8-4f26-11e8-9278-695afd10e71c.png)

## 具体描述
原文中描述点击`测试运行`绘出解决方案（见截图），也就是说点击`测试运行`会生成图片，实际点击之后，反馈框空白。另，代码点击`提交`之后是通过的。

**Comment by UdacityShuwenLiu** [comment]
是的，由于教室中的quiz服务器在国外，所以图片无法显示 QAQ 已经给美国区提需求了
