### ISSUE TITLE
PART2 课程1: 为何要学习 Python 编程 >3.Python 编程>字幕翻译

### ISSUE THREAD

**Issue by leoorpio** [udacity/aipnd-issues-zh#273]
## 翻译内容
PART2 课程1: 为何要学习 Python 编程 >[3.Python 编程](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/410ddff6-0f40-4d69-a63d-22094c21350a/concepts/f705b6bc-5468-4fc8-836c-f88fbe06a6b4)

## 截图
<img width="1212" alt="screenshot" src="https://github.com/leoorpio/issue-pic/blob/master/050401.png?raw=true">

## 具体描述
视频18s处英文字幕翻译：

    Second, spacing is important in Python
    其次 Python 对空格很重视。

建议字幕翻译：

    其次，空格在Python中很重要

**Comment by nicoleliu42** [comment]
感谢反馈！这里的字幕问题已修正！
