### ISSUE TITLE
Numpy, Pandas, Matplotlib > NumPy > 2. NumPy 简介 > 文字表述可改进

### ISSUE THREAD

**Issue by chinaq** [udacity/aipnd-issues-zh#274]
## 课程导航+地址
Numpy, Pandas, Matplotlib > NumPy > [2. NumPy 简介](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/1b5143bb-1d0f-49d7-a3c1-a87c5307260d/concepts/910f8478-dc21-4c3a-943f-9a22e73bc8e8)

## 截图
![2018-05-05_001552](https://user-images.githubusercontent.com/6382133/39638976-82e9e254-4ffa-11e8-91ef-935c1aac1361.png)

## 具体描述
“NumPy 是数字 Python 的简称”，可改为“NumPy 是 Numerical Python 的简称”

**Comment by nicoleliu42** [comment]
感谢反馈！已修改！
