### ISSUE TITLE
Numpy, Pandas, Matplotlib > NumPy > 3. 为何要使用 NumPy？

### ISSUE THREAD

**Issue by chinaq** [udacity/aipnd-issues-zh#275]
## 课程导航+地址
Numpy, Pandas, Matplotlib > NumPy > [3. 为何要使用 NumPy？](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/1b5143bb-1d0f-49d7-a3c1-a87c5307260d/concepts/20562341-873d-4994-9d6b-4634670039bc)

## 截图
![2018-05-05_003147](https://user-images.githubusercontent.com/6382133/39640160-b715d22a-4ffc-11e8-970e-bc3970e4d45a.png)

## 具体描述
“其中一个功能便是速度”，可改为“其中一个优势便是速度”

**Comment by UdacityShuwenLiu** [comment]
@nicoleliu42

**Comment by nicoleliu42** [comment]
感谢反馈！已修改~！
