### ISSUE TITLE
线性代数 -> 课程2: 向量  > 3.什么是向量（第3部分）

### ISSUE THREAD

**Issue by weiweikong** [udacity/aipnd-issues-zh#276]
## 课程导航+地址
课程2 > 向量 > 3.什么是向量（第3部分）
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/120d0c7b-9cd9-4947-86cf-6ddca4d400dc

## 截图
![image 1226](https://user-images.githubusercontent.com/2463397/39659653-e76d65e2-505f-11e8-96a8-955040524d36.jpg)

## 具体描述
视频14s处字幕“一个微朝右向上指， 一个微朝下向上指”，需改为“一个从原点出发朝向右上方，一个从原点出发朝向右下方“

**Comment by UdacityShuwenLiu** [comment]
@nicoleliu42

**Comment by nicoleliu42** [comment]
感谢反馈！已修改~！
