### ISSUE TITLE
线性代数 -> 课程2: 向量 > 4. 向量的数学定义

### ISSUE THREAD

**Issue by weiweikong** [udacity/aipnd-issues-zh#277]
## 课程导航+地址
线性代数 -> 课程2: 向量 > 4. 向量的数学定义
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/0393209e-3dbf-45f4-aa81-6e38b5b66a08
## 截图
![image 1225](https://user-images.githubusercontent.com/2463397/39659666-3ca5603c-5060-11e8-97b8-1196aa8cba50.jpg)

### 原始文本
要计算运动方向，我们将使用夹角。我们可以用度数或半径来表示。在此示例中，我们将采用度数（我们始终可以将度数转换为半径，反之亦然）。

### 修改为：
我们可以用角度或弧度来表示夹角。在此实例中，我们采用弧度来表达。（链接可以查看弧度与角度之间相互转换的计算公式）

**Comment by UdacityShuwenLiu** [comment]
@nicoleliu42

**Comment by nicoleliu42** [comment]
感谢反馈！已修改~！
