### ISSUE TITLE
5，非监督学习 > 课程3，课程4，课程8> 资料包

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#278]
## 课程导航+地址
5，非监督学习 > 层次聚类法和密度聚类 > 资料包
## 截图
![image](https://user-images.githubusercontent.com/34020359/39662917-237d853a-509c-11e8-860a-cb60a3d06ef1.png)

## 具体描述
资料包不全

**Comment by UdacityShuwenLiu** [comment]
已经生成 感谢！
