### ISSUE TITLE
6，强化学习 > 课程9，课程11，课程12> 资料包缺失

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#279]
## 课程导航+地址
6，强化学习 > 课程9，课程11，课程12> 资料包缺失

https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/7f9a6f80-b67d-4b6c-b59b-91aa2e134734/concepts/7508ac67-a221-447d-b8bd-e9baaf381956

https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/aeceac62-e015-41ae-9fef-41551ad8b756/concepts/9436ccee-82ef-4795-87e8-52483feb114f

https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/d34af204-cf9d-457d-9967-4b22163d8363/concepts/a3c56777-c4c4-4ffd-8ebf-0672b7bbd95a

## 截图
![image](https://user-images.githubusercontent.com/34020359/39662999-8cb6c56a-509d-11e8-8065-e52f396a3a3d.png)

## 具体描述
视频44s处字幕XXXX，需改为XXXX

**Comment by UdacityShuwenLiu** [comment]
已经生成 感谢反馈：）
