### ISSUE TITLE
神经网络 > 神经网络简介 > 15. Softmax 函数 > quiz 提交成功之后的视频缺失

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#280]
## 课程导航
神经网络 > 神经网络简介 > [15. Softmax 函数](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/9e1364a8-e8b4-4eac-be12-4d44a139f721)

## 具体描述
在这个单元中，要求学员编写softmax函数，在第二个视频内容中，讲解了如何将处理多类别分类问题的输出概率问题，并在quiz中问道，哪个函数会将任何输入数字变成正数？提交正确答案之后，没有解答视频，导致最后一个coding quiz不知从何入手。

**Comment by UdacityShuwenLiu** [comment]
视频在youtube上，暂时无法搬运至国内，已经添加文字暗示学生。感谢提醒
