### ISSUE TITLE
神经网络 > 神经网络简介 >22. Logistic 回归 > 字幕错误

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#282]
## 课程导航
神经网络 > 神经网络简介 >[22. Logistic 回归](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/a5711d6e-abc1-41bc-a242-e8c8a9834f72)

## 截图
![image](https://user-images.githubusercontent.com/18286481/39671402-4a69a86e-514a-11e8-91a0-761d9a830143.png)

## 具体描述
视频2::44处字幕**已经在这里除以n**，应为**m**，这句话也不太通顺。

**Comment by nicoleliu42** [comment]
已修改！感谢反馈！
