### ISSUE TITLE
神经网络 > 神经网络简介 > 23. 梯度下降 > 文字内容不能理解

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#283]
## 课程导航
神经网络 > 神经网络简介 > [23. 梯度下降](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/0d92455b-2fa0-4eb8-ae5d-07c7834b8a56)

## 截图
![image](https://user-images.githubusercontent.com/18286481/39671754-ec9c4a46-5150-11e8-85e8-3f3b8c05e094.png)

## 具体描述
原文：我们可以使用商式计算它
其中，**商式**不知是什么意思，如果不是笔误，建议给出给详细的解释的介绍。

**Comment by nicoleliu42** [comment]
这里的因为原文是 “The reason for this is the following, we can calculate it using the quotient formula”
麻烦 @UdacityShuwenLiu 看一下这个 “quotient formula” 具体指什么哦！

**Comment by UdacityShuwenLiu** [comment]
商式就是指 两个东西作商啦 比如 a/b 。我觉得翻译成“商式”就OK！ @NaughtyFlame @nicoleliu42

**Comment by nicoleliu42** [comment]
感谢淑雯~！那这里就暂时不作修改啦！
