### ISSUE TITLE
神经网络 > 神经网络简介 > 24. 梯度下降算法 > 公式显示异常

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#284]
## 课程导航
神经网络 > 神经网络简介 > 24. 梯度下降算法

## 截图
![image](https://user-images.githubusercontent.com/18286481/39672300-46348dd0-515a-11e8-9bfe-173a32d19de3.png)

## 具体描述
视频下方公式显示异常。

**Comment by UdacityShuwenLiu** [comment]
搞定 谢谢
