### ISSUE TITLE
神经网络 > 神经网络简介 > 26. [Lab] 梯度下降 > 公式错误及建议

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#285]
## 课程导航
神经网络 > 神经网络简介 > [26. [Lab] 梯度下降](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/64f025bd-1d7b-42fb-9f13-8559242c1ec9)

## 截图
![image](https://user-images.githubusercontent.com/18286481/39672764-231242d0-5163-11e8-82ff-b8db89db3f47.png)

## 具体描述
公式中的加号应为减号。
以下截图是运行成功的代码，代码中可以看到，正确的公式是 `weight  - rate * （y_hat - y）`
![image](https://user-images.githubusercontent.com/18286481/39672817-15df16c8-5164-11e8-8c78-5e7b83a5aad0.png)
此外，建议每个函数开头，写出input内容的格式（list，还是float），以及输出的内容。

**Comment by NaughtyFlame** [comment]
另外补充两个建议
*  对学员需要编写的函数，提供几个testcase，在执行`train`函数前，对学员写的四个函数做判断，是否编写错误，如果有错，是哪个函数有错。
* 对于使用lab进行练习的同学，是否有需要在明显的位置提供答案的链接。

**Comment by UdacityShuwenLiu** [comment]
收到 感谢！
