### ISSUE TITLE
神经网络 > 神经网络简介 > 5.更高维度 > 课程内容有误

### ISSUE THREAD

**Issue by stawary** [udacity/aipnd-issues-zh#286]
## 课程导航+地址
神经网络 > 神经网络简介 > 5.更高维度 
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/3a0e2972-89dc-4b08-826a-1011b9b554ac

## 截图
![_20180506204117](https://user-images.githubusercontent.com/26362074/39673394-16de7096-516e-11e8-9a2f-57cec802ed30.png)

## 具体描述
X1~Xn还有1列y总共应该是n+1个columns。

**Comment by UdacityShuwenLiu** [comment]
已修复
