### ISSUE TITLE
神经网络 > 神经网络简介 > 9. 感知器技巧 > 提交答案不显示结果

### ISSUE THREAD

**Issue by stawary** [udacity/aipnd-issues-zh#287]
## 课程导航+地址
神经网络 > 神经网络简介 > 9. 感知器技巧
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/8ea20904-0215-4e44-afa9-bb5a720bd028

## 截图
![_20180506211519](https://user-images.githubusercontent.com/26362074/39673653-d1cffb46-5172-11e8-8d4b-031f89541c40.png)

## 具体描述
提交答案后不显示正确还是错误。

**Comment by UdacityShuwenLiu** [comment]
这个就表示答案正确哦，如果是提交错误的话，会是红色的另一个提示
