### ISSUE TITLE
神经网络 > 课程2.训练神经网络 > 6. 正则化2 > 字幕翻译问题

### ISSUE THREAD

**Issue by stawary** [udacity/aipnd-issues-zh#288]
## 课程导航+地址
神经网络 > 课程2.训练神经网络 > 6. 正则化2
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/1a0c733f-e9a5-4ffb-a905-a7a2de1975bf/concepts/2e0a0320-f6f0-4506-a6b5-0d913fac2fa1

## 截图
![_20180506215148](https://user-images.githubusercontent.com/26362074/39673997-efc6e6b4-5177-11e8-98c4-7b0af0103f90.png)

## 具体描述
此处翻译错误，应翻译为：将其余的变为0。

**Comment by nicoleliu42** [comment]
感谢反馈！已修正！
