### ISSUE TITLE
神经网络 > 课程2.训练神经网络 > 7. Dropout > 字幕翻译问题

### ISSUE THREAD

**Issue by stawary** [udacity/aipnd-issues-zh#289]
## 课程导航+地址
神经网络 > 课程2.训练神经网络 > 7. Dropout
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/1a0c733f-e9a5-4ffb-a905-a7a2de1975bf/concepts/05d1b01f-191e-4b45-8e93-469aa0e05877

## 截图
![_20180506215905](https://user-images.githubusercontent.com/26362074/39674057-e122737a-5178-11e8-9f9d-1d2a35b3bf28.png)

## 具体描述
此处dominant hand翻译错误，应翻译为惯用手而不一定是右手。

**Comment by nicoleliu42** [comment]
感谢反馈！字幕已修正！
