### ISSUE TITLE
神经网络 > 神经网络简介 > 32. 前向反馈 > 公式显示异常

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#290]
## 课程导航+地址
神经网络 > 神经网络简介 > [32. 前向反馈](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/02c36864-ee71-481c-bb01-a34c35bfc581)

## 截图
![image](https://user-images.githubusercontent.com/18286481/39674119-cb1c9f1e-5179-11e8-9c48-36f67d15073a.png)

**Comment by UdacityShuwenLiu** [comment]
搞定
