### ISSUE TITLE
神经网络 > 神经网络简介 > 33. 反向传播 > 需要额外补充内容

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#291]
## 课程导航
神经网络 > 神经网络简介 > [33. 反向传播](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/4cc13714-37d7-4705-a714-314ede5290b5)

## 截图
![image](https://user-images.githubusercontent.com/18286481/39674559-441d1d66-5180-11e8-822e-26780dad2da4.png)

## 具体描述
截图中，提到**keras**很突兀，对于初学者，这个框架的名字很陌生。可以说，如果不想听也没有关系，现有的很多代码库和深度学习框架比如[keras](https://keras.io/zh/)，能够很好并且很简单地完成这个任务。

**Comment by UdacityShuwenLiu** [comment]
已修复 很有帮助！ 感谢！！
