### ISSUE TITLE
神经网络 > 神经网络简介 > 34. 实验准备: 分析学生数据 > 翻译生硬

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#292]
## 课程导航+地址
神经网络 > 神经网络简介 > [34. 实验准备: 分析学生数据](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/964e9bdb-40c3-4110-aee7-fddd13bea0c6)

## 截图
![image](https://user-images.githubusercontent.com/18286481/39674754-4e7f6fa4-5183-11e8-9e0c-ba15fbd5064b.png)

## 具体描述
文中，**从github克隆**，翻译生硬且奇怪，保留原来的clone更加好。

**Comment by nicoleliu42** [comment]
感谢反馈！已修改！
