### ISSUE TITLE
神经网络 > 神经网络简介 > 35. 分析学生数据 > notebook未翻译

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#293]
## 课程导航 
神经网络 > 神经网络简介 > [35. 分析学生数据](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/dab588a2-51cc-4c4e-ba24-410a009943c7#)

## 具体描述
这个文件没有翻译。

**Comment by nicoleliu42** [comment]
感谢你的反馈！麻烦 @sylviasun916 看看这个workspace的问题哦
另外麻烦 @UdacityShuwenLiu 看看第二个问题应该如何解决？

**Comment by sylviasun916** [comment]
已翻译，谢谢反馈！ 

麻烦 @UdacityShuwenLiu 看看第二个问题应该如何补充信息解决哦？谢谢 。
