### ISSUE TITLE
线性代数 -> 课程3: 线性组合 > 3. 线性组合和张成

### ISSUE THREAD

**Issue by kinghonglee** [udacity/aipnd-issues-zh#299]
## 课程导航+地址
[线性代数 -> 课程3: 线性组合 > 3. 线性组合和张成](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/7944df46-7a24-45ac-a27d-ac6620667108/concepts/29d25468-2ac0-4a9f-ac21-962c4765f498)

## 截图
![image](https://user-images.githubusercontent.com/31353264/39681168-f56b36fc-51da-11e8-943c-6e9833b03f16.png)
![image](https://user-images.githubusercontent.com/31353264/39681169-f90b551c-51da-11e8-8056-28365d5ae80a.png)
![image](https://user-images.githubusercontent.com/31353264/39681171-fc1e1992-51da-11e8-9424-f1477fe05e37.png)

## 具体描述
“方程6”，“方程7”，“方程8”我觉得写在方程的上面比较好！

**Comment by nicoleliu42** [comment]
感谢你的细心反馈！这里我们保留了英文原文的格式，所以暂时不做修改哦！
另外，可不可以麻烦你今后在标题中添加反馈问题的大概内容，比如“翻译错误”、“字幕错误”、“链接/图片缺失”等，方便我们及时进行处理呀？感谢你的配合！
