### ISSUE TITLE
线性代数 > 课程4> 8. 矩阵乘法练习> 习题答案

### ISSUE THREAD

**Issue by kinghonglee** [udacity/aipnd-issues-zh#300]
## 课程导航+地址
[线性代数 > 课程4> 8. 矩阵乘法练习> 习题答案](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/d9334d0c-1a33-4913-8b21-a643a8d7a2a0/concepts/0bdd2955-58fa-4d53-a07d-450d5b89185d)

## 截图
![image](https://user-images.githubusercontent.com/31353264/39733321-ca14c39a-52a4-11e8-904f-4981c417829f.png)

## 具体描述
最后一个问题没有有效解，能不能设定一个字符串或者一个有效的值作为答案通过一下题目的验证

**Comment by UdacityShuwenLiu** [comment]
正确答案是error，已经提示学生。
