### ISSUE TITLE
线性代数 > 课程4> 9. f线性变换和矩阵第一部分> 翻译问题

### ISSUE THREAD

**Issue by kinghonglee** [udacity/aipnd-issues-zh#301]
## 课程导航+地址
[线性代数 > 课程4> 9. f线性变换和矩阵第一部分> 翻译问题](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/d9334d0c-1a33-4913-8b21-a643a8d7a2a0/concepts/302286d4-4d8f-40aa-aba1-998fa7136446)

## 截图

![image](https://user-images.githubusercontent.com/31353264/39733540-cdf6ee92-52a5-11e8-9b0d-5416cd4902fa.png)

## 具体描述
视频17s处字幕“统合”，需改为“整合”

**Comment by nicoleliu42** [comment]
感谢你的细心反馈！“统合”其实就是“统一、综合”的意思哦，所以这里暂时不作修改！
