### ISSUE TITLE
神经网络 > 通过pytorch进行深度学习 > 3.PyTorch张量 > 内容建议

### ISSUE THREAD

**Issue by stawary** [udacity/aipnd-issues-zh#303]
## 课程导航+地址
神经网络 > 通过pytorch进行深度学习 > 3.PyTorch张量 
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/e1eeafe1-2ba0-4f3d-97a0-82cbd844fdfc/concepts/cbab7cc5-3456-4e01-8cac-09c1d2a6b750

## 截图
![_20180508165238](https://user-images.githubusercontent.com/26362074/39747838-fb03b1c8-52e0-11e8-95bc-758e91e67a1d.png)

## 具体描述
既然是本土化的课程，那么给学员看到的应该是中文版本的ipynb，同时，想看英文原版的ipynb给出链接可自行查看。

**Comment by nicoleliu42** [comment]
感谢你的反馈 麻烦 @CheneyZeng 修改一下默认路径哦

**Comment by nicoleliu42** [comment]
感谢你的反馈！麻烦 @UdacityShuwenLiu 修改一下默认路径哦！

**Comment by UdacityShuwenLiu** [comment]
已修复
