### ISSUE TITLE
神经网络 > 训练神经网络 > 9.梯度消失 > 字幕翻译问题

### ISSUE THREAD

**Issue by stawary** [udacity/aipnd-issues-zh#304]
## 课程导航+地址
神经网络 > 训练神经网络 > 9.梯度消失
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/1a0c733f-e9a5-4ffb-a905-a7a2de1975bf/concepts/f39bf14a-ddc9-4560-99b5-be8eff82fac6

## 截图

![_20180508170741](https://user-images.githubusercontent.com/26362074/39748694-4fe89d5a-52e3-11e8-8d5d-221915fc6d69.png)

## 具体描述
个人认为此处可直接翻译为sigmoid函数，比s型函数要好。

**Comment by nicoleliu42** [comment]
感谢你的细心反馈！对于这个术语，google提供的术语表翻译为“s型函数”，维基百科翻译为“s函数”，所以我们觉得这里的翻译是不影响学员理解的哦！因此暂时不作修改~
