### ISSUE TITLE
神经网络 > 训练神经网络 > 10. 其他激活函数 > 自动跳转设置

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#305]
## 课程导航+地址
神经网络 > 训练神经网络 > [10. 其他激活函数](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/1a0c733f-e9a5-4ffb-a905-a7a2de1975bf/concepts/79a26389-34e8-4b3b-9cae-29f6ed792ba6)

## 具体描述
这个章节下面有文字作为补充内容，但是此单元视频播放完毕会自动跳转，文字内容在视频下方，页面之外，非常容易忽略下面的内容。

**Comment by UdacityShuwenLiu** [comment]
唔，暂时无解，感谢提出
