### ISSUE TITLE
线性代数> 课程6 > 线性组合lab> 代码问题

### ISSUE THREAD

**Issue by kinghonglee** [udacity/aipnd-issues-zh#306]
## 课程导航+地址
[线性代数> 课程6 > 线性组合lab> 代码问题](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/8c33429f-5230-43e3-9e1b-8e8e29372f3a/concepts/358da297-a2d4-45c2-a43b-6a9562c2f901#)

## 截图
![image](https://user-images.githubusercontent.com/31353264/39848683-ee591034-543a-11e8-8968-394b507fa4ae.png)
![image](https://user-images.githubusercontent.com/31353264/39848750-5a5a9a78-543b-11e8-82f5-cb03fc9c6cf2.png)

![image](https://user-images.githubusercontent.com/31353264/39848883-2e7cedd8-543c-11e8-8dbc-39c926469eac.png)

## 具体描述
显示结果的这一行可能还是要处理一下，不然会显示报错！

**Comment by UdacityShuwenLiu** [comment]
搞定
