### ISSUE TITLE
线性代数> 课程6 > 线性组合lab> 链接问题

### ISSUE THREAD

**Issue by kinghonglee** [udacity/aipnd-issues-zh#307]
## 课程导航+地址
[线性代数> 课程6 > 线性组合lab> 代码问题](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/8c33429f-5230-43e3-9e1b-8e8e29372f3a/concepts/358da297-a2d4-45c2-a43b-6a9562c2f901#)

## 截图
![image](https://user-images.githubusercontent.com/31353264/39848988-ba5276ca-543c-11e8-86f0-d9f720d56787.png)
![image](https://user-images.githubusercontent.com/31353264/39849039-fca61f5e-543c-11e8-822f-f3b59c758caf.png)
![image](https://user-images.githubusercontent.com/31353264/39849052-0f1f4be2-543d-11e8-81f5-5e77d470dcf6.png)

## 具体描述
点击此处页面无法显示

**Comment by UdacityShuwenLiu** [comment]
搞定
