### ISSUE TITLE
线性代数> 课程5> 线性组合lab> 链接问题

### ISSUE THREAD

**Issue by kinghonglee** [udacity/aipnd-issues-zh#308]
## 课程导航+地址
[线性代数> 课程5> 线性组合lab> 链接问题](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/1d0cd6f3-41eb-49c0-b1bb-3746eced5a97/concepts/1f9246d1-4879-4bca-a2a8-6a9629347795#)

## 截图

![image](https://user-images.githubusercontent.com/31353264/39849141-7cabdff4-543d-11e8-99b0-dcad48cd59b4.png)
![image](https://user-images.githubusercontent.com/31353264/39849153-8c65d170-543d-11e8-8c5b-62e59700ecfb.png)

## 具体描述
点击此处链接打不开

**Comment by UdacityShuwenLiu** [comment]
已删去 感谢
