### ISSUE TITLE
线性代数> 课程6 > 线性组合lab> 一点建议

### ISSUE THREAD

**Issue by kinghonglee** [udacity/aipnd-issues-zh#310]
## 课程导航+地址
[线性代数> 课程6 > 线性组合lab> ](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/8c33429f-5230-43e3-9e1b-8e8e29372f3a/concepts/358da297-a2d4-45c2-a43b-6a9562c2f901#)

## 截图

![image](https://user-images.githubusercontent.com/31353264/39849477-1cf2b928-543f-11e8-9dca-e0bd92c59273.png)

## 具体描述
能不能在课程的左边加上解决方案的链接！

**Comment by UdacityShuwenLiu** [comment]
已修复 感谢
