### ISSUE TITLE
线性代数> 课程7> 线性映射> 图片无法显示

### ISSUE THREAD

**Issue by kinghonglee** [udacity/aipnd-issues-zh#311]
## 课程导航+地址
[线性代数> 课程7> 线性映射> 图片无法显示](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/872aea9e-6e18-4104-8358-4e4d96d4ae45/concepts/84850c41-5a08-4ce7-9a6e-4299c2b0f045#)

## 截图

![image](https://user-images.githubusercontent.com/31353264/39850140-60dc20b8-5442-11e8-97cc-c211eaadd649.png)

![image](https://user-images.githubusercontent.com/31353264/39850938-954bf464-5446-11e8-81f0-458b598e2634.png)

## 具体描述
图片无法显示！

**Comment by UdacityShuwenLiu** [comment]
已删去 感谢
