### ISSUE TITLE
欢迎学习人工智能编程基础纳米学位 > 简介 > 3社区支持

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#312]
## 课程导航+地址
欢迎学习人工智能编程基础纳米学位 > 简介 > 3社区支持

## 截图
![image](https://user-images.githubusercontent.com/34020359/39853832-1b6c4d5e-5457-11e8-85fa-7737c6981a21.png)

## 具体描述
我们没有这个吧？

**Comment by UdacityShuwenLiu** [comment]
已删除，感谢
