### ISSUE TITLE
线性代数> 课程7> 线性映射> 链接问题

### ISSUE THREAD

**Issue by kinghonglee** [udacity/aipnd-issues-zh#313]
## 课程导航+地址
[线性代数> 课程7> 线性映射> 链接问题](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/872aea9e-6e18-4104-8358-4e4d96d4ae45/concepts/84850c41-5a08-4ce7-9a6e-4299c2b0f045#)

## 截图
![image](https://user-images.githubusercontent.com/31353264/39854770-c4e53be4-545b-11e8-808b-da9d0b72bada.png)
![image](https://user-images.githubusercontent.com/31353264/39854797-e521dbc4-545b-11e8-8b8a-9df485d1b089.png)

## 具体描述
图中此处所对应的链接问题

**Comment by UdacityShuwenLiu** [comment]
已修复
