### ISSUE TITLE
线性代数> 课程8> 神经网络中的线性代数> 字幕问题

### ISSUE THREAD

**Issue by kinghonglee** [udacity/aipnd-issues-zh#314]
[## 课程导航+地址
线性代数> 课程8> 神经网络中的线性代数> 字幕问题](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/9030e3b5-5e66-4e2b-97a3-351758b5f1f6/concepts/ebc4a2f1-066c-4805-ae3a-6e1e2e7738bf)
## 截图
![image](https://user-images.githubusercontent.com/31353264/39857905-89b315b2-5467-11e8-82ea-a5f9e68f9d24.png)

## 具体描述
视频14s处字幕“于”，需改为“与”

**Comment by UdacityShuwenLiu** [comment]
@nicoleliu42

**Comment by nicoleliu42** [comment]
感谢反馈！这里的字幕已经修正啦~
