### ISSUE TITLE
Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn（第 1 部分） > 6. 计算缺失的数据 ＞ 文字描述是否可改进

### ISSUE THREAD

**Issue by chinaq** [udacity/aipnd-issues-zh#315]
## 课程导航+地址
Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn（第 1 部分） > [6. 计算缺失的数据](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/43855abb-dae5-46c7-9167-4b001dabd41e/concepts/undefined) ＞ 文字描述是否可改进

## 截图
![2018-05-11_094543](https://user-images.githubusercontent.com/6382133/39902490-cf7146a2-5500-11e8-80a4-183f2f7a270a.png)

## 具体描述
此处“摘要”一词不太理解和其含义，不知原文为何，是否可改进

**Comment by nicoleliu42** [comment]
感谢反馈！这里的翻译已优化！
