### ISSUE TITLE
Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn（第 ２ 部分） > ５. 小提琴图 ＞　缺少视频

### ISSUE THREAD

**Issue by chinaq** [udacity/aipnd-issues-zh#317]
## 课程导航+地址
Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn（第 ２ 部分） > [５. 小提琴图](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/0491d74e-dcd8-4700-a971-a7f1b0a26ddb/concepts/1dca3bcb-d2d4-44c2-b88e-ecea98402349)  > 缺少视频

## 截图
![2018-05-11_151255](https://user-images.githubusercontent.com/6382133/39911452-05acda4c-552e-11e8-9202-e254955d57ea.png)

## 具体描述
缺少视频

**Comment by UdacityShuwenLiu** [comment]
搞定 感谢
