### ISSUE TITLE
Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn（第 ２ 部分） > ６. 箱线图  > 字幕问题

### ISSUE THREAD

**Issue by chinaq** [udacity/aipnd-issues-zh#318]
## 课程导航+地址
Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn（第 ２ 部分） > [６. 箱线图](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/0491d74e-dcd8-4700-a971-a7f1b0a26ddb/concepts/6ec37bb1-2d14-451c-9965-91c86be93be3)  > 字幕问题

## 截图
![2018-05-11_152218](https://user-images.githubusercontent.com/6382133/39911972-b89a27c6-552f-11e8-9932-1d7e8814dd68.png)

## 具体描述
没有“西队”🤣，应该是“南队”吧

**Comment by nicoleliu42** [comment]
感谢反馈~这里的字幕已经修正啦！
