### ISSUE TITLE
Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn（第 ２部分） > ９. 调整单变量图形＞ 00:56 以后没字幕了

### ISSUE THREAD

**Issue by chinaq** [udacity/aipnd-issues-zh#319]
## 课程导航+地址
Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn（第 ２部分） > [９. 调整单变量图形](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/0491d74e-dcd8-4700-a971-a7f1b0a26ddb/concepts/c2627efd-b028-430f-b3f8-de1d17e9db89) ＞ 00:56 以后没字幕了

## 截图
![2018-05-11_163603](https://user-images.githubusercontent.com/6382133/39915145-b5d4e09e-5539-11e8-9ec0-69911f626425.png)

## 具体描述
00:56 以后没字幕了

**Comment by sylviasun916** [comment]
中文字幕已解决。 英文字幕需要工程支持。 谢谢。
