### ISSUE TITLE
神经网络 > 通过pytorch进行深度学习 > 3. Pytorch张量 > workspace有多余无效内容

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#321]
## 课程导航
神经网络 > 通过pytorch进行深度学习 > [3. Pytorch张量](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/e1eeafe1-2ba0-4f3d-97a0-82cbd844fdfc/concepts/cbab7cc5-3456-4e01-8cac-09c1d2a6b750)

## 截图
![capture1](https://user-images.githubusercontent.com/18286481/39929659-39d27bdc-556b-11e8-926a-d5370e6f9c14.png)

## 具体描述
workspace中，每个输出之后都有文字形式的输出，但是因为是随机的，学员的shuju数据和文字是不符的。

**Comment by UdacityShuwenLiu** [comment]
已解决
