### ISSUE TITLE
神经网络 > 通过PyTorch进行深度学习 > 4.定义网络 > 课程内容建议

### ISSUE THREAD

**Issue by stawary** [udacity/aipnd-issues-zh#324]
## 课程导航+地址
神经网络 > 通过PyTorch进行深度学习 > 4.定义网络
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/e1eeafe1-2ba0-4f3d-97a0-82cbd844fdfc/concepts/b21f290b-6ef8-4679-851b-a38245d477d8
## 截图
![_20180512193952](https://user-images.githubusercontent.com/26362074/39956918-4680bfe0-561c-11e8-9b1a-bbb5c87d1b66.png)

## 具体描述
之前在课程3.PyTorch张量 中提出过建议，默认ipynb为中文版本，现课程3已修改，但课程4、5均未修改。

**Comment by UdacityShuwenLiu** [comment]
已搞定
