### ISSUE TITLE
神经网络 > 通过PyTorch进行深度学习 > 5.训练网络 > 内容有误

### ISSUE THREAD

**Issue by stawary** [udacity/aipnd-issues-zh#325]
## 课程导航+地址
神经网络 > 通过PyTorch进行深度学习 > 5.训练网络 
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/e1eeafe1-2ba0-4f3d-97a0-82cbd844fdfc/concepts/b714c17e-9eda-4f76-a59e-a05ae8318297

## 截图
![_20180512194306](https://user-images.githubusercontent.com/26362074/39956931-b541877a-561c-11e8-8c78-4f5e8ad71a45.png)

## 具体描述
截图出红圈部分应为 ∂ℓ 而不是 ∂C。同时需修改默认路径为中文ipynb。

**Comment by UdacityShuwenLiu** [comment]
感谢提醒 此部分内容已更新
