### ISSUE TITLE
神经网络 > 通过PyTorch进行深度学习 > 5.训练网络 > workspace中有无法显示的图片

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#326]
## 课程导航+地址
神经网络 > 通过PyTorch进行深度学习 > [5.训练网络](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/e1eeafe1-2ba0-4f3d-97a0-82cbd844fdfc/concepts/b714c17e-9eda-4f76-a59e-a05ae8318297)

## 截图
![image](https://user-images.githubusercontent.com/18286481/39965287-b1929004-56c8-11e8-82a2-2a20ecf7f08f.png)

## 具体描述
此课workspace底部有无法显示的图片。

**Comment by UdacityShuwenLiu** [comment]
搞定
