### ISSUE TITLE
神经网络 > 通过PyTorch进行深度学习 > 6.Fashion-MNIST练习 > 内容建议

### ISSUE THREAD

**Issue by stawary** [udacity/aipnd-issues-zh#329]
## 课程导航+地址
神经网络 > 通过PyTorch进行深度学习 > 6.Fashion-MNIST练习
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/23055792-a4f4-4ed7-aa59-3fe7516c2fcc/concepts/5802a10d-5ab0-46a4-bb49-97d3e10f4873

## 截图

![360 20180514142122753](https://user-images.githubusercontent.com/26362074/39981427-2393ffb6-5783-11e8-8f22-603a621da396.jpg)

## 具体描述
建议如图中所示，上文导读说：“在这里，我们能看到其中一张图片”，但是运行后没有图片。建议加上以下代码即可出现图片。
import matplotlib.pyplot as plt
%matplotlib inline

**Comment by UdacityShuwenLiu** [comment]
已修复 感谢
