### ISSUE TITLE
2 python入门>课程5脚本编写>26第三方库>链接无效

### ISSUE THREAD

**Issue by lonelytechreader** [udacity/aipnd-issues-zh#331]
例子：进阶 >2 python入门>课程5脚本编写>26第三方库>链接失效
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/45252bd7-50b1-41f0-bed5-cef100501c12
## 截图
![qq 20180515211600](https://user-images.githubusercontent.com/38041963/40059109-c386dc7a-5885-11e8-86a0-7aaf86fd3edc.png)
![qq 20180515211626](https://user-images.githubusercontent.com/38041963/40059115-c9f1c34a-5885-11e8-88a4-f9d4fe2fb537.png)
![qq 20180515211911](https://user-images.githubusercontent.com/38041963/40059122-d1b563d4-5885-11e8-940f-6a5e1c18ca5d.png)

## 具体描述
pillow,pytz链接打开不了

**Comment by UdacityShuwenLiu** [comment]
已提醒学员 感谢！
