### ISSUE TITLE
神经网络 > 通过PyTorch进行深度学习 > 第7-9课 > 视频无中文字幕

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#332]
## 课程导航
神经网络 > 通过PyTorch进行深度学习 > [7.推理和验证](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/23055792-a4f4-4ed7-aa59-3fe7516c2fcc/concepts/43cb782f-2d8c-432e-94ef-cb8068f26042)

## 截图
![image](https://user-images.githubusercontent.com/18286481/40065986-a361f2f8-5895-11e8-9fa0-a49c478d6e2a.png)

## 具体描述
上方是第七课的链接和截图，剩余的几课有同样的问题

**Comment by nicoleliu42** [comment]
感谢反馈~这部分的字幕已经在汉化了哦 很快就会部署上线
