### ISSUE TITLE
线性代数 -> 课程3：线性组合 ->3.线性组合和张成

### ISSUE THREAD

**Issue by weiweikong** [udacity/aipnd-issues-zh#333]
## 课程导航+地址
线性代数 -> 课程3：线性组合 ->3.线性组合和张成
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/7944df46-7a24-45ac-a27d-ac6620667108/concepts/29d25468-2ac0-4a9f-ac21-962c4765f498

## 截图
![image](https://user-images.githubusercontent.com/2463397/40264096-51dc326a-5b4f-11e8-90b2-f0cc7daabd6b.png)

## 具体描述
- 方程编号位置应该在公式后方，这样排版更好看。后续诸多页面的公式排版，都有这个问题。
- 线性组合是指将标量与变量相乘 --> 线性组合是指将标量与向量相乘
- "span any vector in ..." 没有翻译 -> v1, v2, v3可以张成R3空间中的任意向量。

**Comment by UdacityShuwenLiu** [comment]
搞定 感谢
