### ISSUE TITLE
线性代数 -> 课程3：线性组合 ->4.矩阵的标量乘法练习

### ISSUE THREAD

**Issue by weiweikong** [udacity/aipnd-issues-zh#334]
## 课程导航+地址
线性代数 -> 课程3：线性组合 ->4.矩阵的标量乘法练习
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/d9334d0c-1a33-4913-8b21-a643a8d7a2a0/concepts/7684aecd-d2a7-4a09-8b47-35855299c23f

## 截图
![image](https://user-images.githubusercontent.com/2463397/40264130-0d10b3c6-5b50-11e8-86cf-c355c8d1d625.png)

## 具体描述
图中的翻译无法理解。请参照英文重新翻译。

**Comment by UdacityShuwenLiu** [comment]
@nicoleliu42

**Comment by nicoleliu42** [comment]
感谢反馈！已修改翻译！
