### ISSUE TITLE
2 python入门>课程8 Lab:分类图像>13 将标签分类成小狗>视频播放不了

### ISSUE THREAD

**Issue by lonelytechreader** [udacity/aipnd-issues-zh#335]
## 课程导航+地址
例子：进阶 > 2 python入门>课程8 Lab:分类图像>13 将标签分类成小狗>视频播放不了
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/f8c19d5d-077d-4a0d-89db-08b8fd9fbcd2/lessons/d79396c0-8fa6-4adc-ac06-9d9649fb0525/concepts/356e8d82-0ba2-49d4-b846-867a343764e7
## 截图
![qq 20180519152303](https://user-images.githubusercontent.com/38041963/40266150-a157a0c6-5b78-11e8-926f-c99d193627c0.png)

## 具体描述
视频播放不了

**Comment by UdacityShuwenLiu** [comment]
已修复
