### ISSUE TITLE
神经网络 > 通过PyTorch进行深度学习 > 9. 使用torchvision加载数据集 > workspace内容问题

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#337]
## 课程导航
神经网络 > 通过PyTorch进行深度学习 > [9. 使用torchvision加载数据集](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/23055792-a4f4-4ed7-aa59-3fe7516c2fcc/concepts/c89c7648-75a5-405a-aec9-23b6a7ad5150)

## 截图
![image](https://user-images.githubusercontent.com/18286481/40268996-7feb6418-5baa-11e8-8b85-dcb1fd54b693.png)

## 具体描述
在练习之前，有大段的讲解内容，在讲解部分，出现了很多实际代码，但是那些代码是示例代码，无法正确运行（路径错误），建议将此处的代码都写在markdown文本内容之中。此外第八课中，也有输出内容复制到代码块中，略显累赘。

**Comment by NaughtyFlame** [comment]
下方图片显示异常。

![image](https://user-images.githubusercontent.com/18286481/40269138-6f20c5b8-5bac-11e8-80b4-b58eae6d4aea.png)

**Comment by NaughtyFlame** [comment]
代码块和文字部分没有分离
![image](https://user-images.githubusercontent.com/18286481/40269284-0368b76a-5baf-11e8-9567-73a0000b6aea.png)

**Comment by NaughtyFlame** [comment]
这里部分，变量`transforms`命名很差，此处运行之后，变成一个compose的类，而不是从外部调用的`transforms`函数了，所以二次运行以后会出现一下问题。建议将变量名修改。否则也会对下面的练习有影响。
![image](https://user-images.githubusercontent.com/18286481/40269322-b9efde0a-5baf-11e8-91e7-a433739b6ff8.png)

**Comment by NaughtyFlame** [comment]
文件路径有误，应该为`../Cat_Dog_data`
![image](https://user-images.githubusercontent.com/18286481/40269411-adca080c-5bb0-11e8-884b-d74386416355.png)

**Comment by UdacityShuwenLiu** [comment]
收到 感谢！
