### ISSUE TITLE
神经网络 > 通过PyTorch进行深度学习 > 10. 迁移学习 > workspace中 gpu无法使用，练习报错

### ISSUE THREAD

**Issue by NaughtyFlame** [udacity/aipnd-issues-zh#339]
## 课程导航
神经网络 > 通过PyTorch进行深度学习 > [10. 迁移学习](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/23055792-a4f4-4ed7-aa59-3fe7516c2fcc/concepts/a5a19eea-896f-4553-bb7c-fb17b9be70ae)

## 截图
![image](https://user-images.githubusercontent.com/18286481/40270152-c9b9926c-5bba-11e8-9862-e653047f122a.png)

## 具体描述
这个练习之中，会比较cpu和gpu的性能，但是workspace中不能使用gpu。

**Comment by UdacityShuwenLiu** [comment]
是可用的，每个人有gpu的倒计时使用时间，感谢
