### ISSUE TITLE
项目二 电影分析

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#341]
## 课程导航+地址
项目二 电影分析

## 截图
![image](https://user-images.githubusercontent.com/34020359/40587942-de5f8614-6208-11e8-9365-60860ed52afd.png)

csv文件在哪里

## 具体描述
1、图的下方
2、第一印象，题目有点太简陋了，捂脸

**Comment by UdacityShuwenLiu** [comment]
[TMDb电影数据](https://s3.cn-north-1.amazonaws.com.cn/static-documents/nd101/explore+dataset/tmdb-movies.csv)
