### ISSUE TITLE
神经网络   - 通过pytorch进行深度学习 - 迁移学习 - 对应的jupyter 不对【严重问题】

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#342]
## 课程导航+地址
神经网络   - 通过pytorch进行深度学习 - 迁移学习- 对应的jupyter 不对【严重问题】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/23055792-a4f4-4ed7-aa59-3fe7516c2fcc/concepts/a5a19eea-896f-4553-bb7c-fb17b9be70ae

## 截图
![image](https://user-images.githubusercontent.com/34020359/40634474-d0a1636a-6327-11e8-9623-9d5b9c85a954.png)

## 具体描述
对应的jupyter不对

**Comment by UdacityShuwenLiu** [comment]
已修复 感谢
