### ISSUE TITLE
神经网络 > 通过PyTorch进行深度学习 > 10. 迁移学习> 第二个cell加载数据集时报错（无文件夹）

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#344]
## 课程导航+地址
神经网络 > 通过PyTorch进行深度学习 > 10. 迁移学习> 第二个cell加载数据集时报错（无文件夹）

## 截图
![image](https://user-images.githubusercontent.com/34020359/40701572-01772f12-6411-11e8-8321-f7d040be9562.png)

## 具体描述
 第二个cell加载数据集时报错（无文件夹）

**Comment by UdacityShuwenLiu** [comment]
搞定，谢谢
