### ISSUE TITLE
Numpy, Pandas and Matplotlib > 1. Numpy > 4. 创建和保存 NumPy ndarray > 字幕问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#345]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/1b5143bb-1d0f-49d7-a3c1-a87c5307260d/concepts/cf9e2370-5bc1-4ed6-9a59-9996606a8448

## 截图
![image](https://user-images.githubusercontent.com/5260728/40868849-187a446c-6644-11e8-97d7-579f966220b1.png)

## 具体描述
视频1分18秒处，英文字幕“assigned 64-bit integers”不对，结合上下文看应该是“a signed 64-bit integers”，指ndarray中存放的是有符号的64位整数。连带中文翻译也错了，请改正，谢谢。

**Comment by UdacityShuwenLiu** [comment]
@nicoleliu42

**Comment by nicoleliu42** [comment]
感谢反馈！已修改！字幕稍后会重新部署上线！
