### ISSUE TITLE
Numpy, Pandas and Matplotlib > 1. Numpy > 9. 布尔型索引、集合运算和排序 > 视频无法加载

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#347]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/1b5143bb-1d0f-49d7-a3c1-a87c5307260d/concepts/42233fd3-32a0-424d-84b3-49b96e44f1e1

## 截图
![image](https://user-images.githubusercontent.com/5260728/40869848-d200f830-6654-11e8-8c4f-8dc32555d832.png)

## 具体描述
视频区域一片空白，没有成功加载，火狐浏览器也是一样问题

**Comment by UdacityShuwenLiu** [comment]
已修复

**Comment by leesper** [comment]
@UdacityShuwenLiu 问题仍然存在~
