### ISSUE TITLE
项目一 机器人走迷宫

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#349]
## 课程导航+地址
项目一 机器人走迷宫

## 截图
![image](https://user-images.githubusercontent.com/34020359/41040668-a365edea-69cf-11e8-92bc-b7b15d3a3268.png)

## 具体描述
错别字，列数

**Comment by nicoleliu42** [comment]
麻烦 @UdacityShuwenLiu  修改一下Github里的文件哦~！

**Comment by sylviasun916** [comment]
已经修改过啦，谢谢各位。
