### ISSUE TITLE
python --课程3 控制流----7----解答有问题

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#350]
## 课程导航+地址
例子：python --课程3 控制流----7----解答有问题
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/0dc5b22c-4b87-4ce4-b23f-b35b0d5fa996

## 截图
![image](https://user-images.githubusercontent.com/34020359/41140433-26e31a8e-6b20-11e8-9d70-c4d33d482b1d.png)

## 具体描述
去掉have，否则答案测试不通过

**Comment by DrTrippleJ** [comment]
已经解决，谢谢
