### ISSUE TITLE
Python入门 > 2. 数据类型和运算符 > 4. 变量和赋值运算符 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#352]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/cf20e9f1-9b19-4bea-b2e1-d5c591e20877

## 截图
![image](https://user-images.githubusercontent.com/5260728/41202400-3414d814-6cfb-11e8-9f99-10d5db2e63ac.png)

## 具体描述
翻译很拗口，“在任何情况下，无论左侧的项是什么，现在都是右侧无论什么值的名称。一旦将值赋给变量名称，你就可以通过变量名称访问该值。”

**Comment by nicoleliu42** [comment]
感谢你的反馈！这里的文本已经优化~！
