### ISSUE TITLE
Python入门 > 2. 数据类型和运算符 > 29. 练习：复合数据结构 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#353]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/788a3fa5-e1be-41ba-aab4-afad0a60b23b

## 截图
![image](https://user-images.githubusercontent.com/5260728/41524267-7927f0ca-730f-11e8-943a-1c577d99871b.png)

## 具体描述
这里翻译似乎有问题，“可序性”是指可排序的意思吗？还需要确认下原来的英文是啥，谢谢

**Comment by sylviasun916** [comment]
感谢反馈！ 是可排序 sortable 的意思，已改为 "可排序“ 方便大家理解，谢谢！
