### ISSUE TITLE
Python入门 > 2. 数据类型和运算符 > 29. 练习：复合数据结构 > 习题问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#354]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/788a3fa5-e1be-41ba-aab4-afad0a60b23b

## 截图
![image](https://user-images.githubusercontent.com/5260728/41524357-c65b8cee-730f-11e8-96d9-bbe059d202a2.png)

## 具体描述
这里的最后一个选项“可以嵌套”有待商榷，因为list其实也是可以嵌套的，tuple也可以嵌套，实际上跑一趟python的很多数据结构都可以嵌套，这并不是dict才有的特点。

另外，对列表而言，有个常见错误用法课程中没有提到，我觉得可以在适当地方提一下，就是如果列表a.append(b)，b本身是个列表的，话，a就会把列表b塞进去，而不是把列表b的元素放到a中：
In [6]: a = [1,2,3]
In [7]: b = [4,5,6]
In [8]: a.append(b)
In [9]: a
Out[9]: [1, 2, 3, [4, 5, 6]]
正确做法应该是：
In [10]: a = [1,2,3]
In [11]: b = [4,5,6]
In [12]: a += b
In [13]: a
Out[13]: [1, 2, 3, 4, 5, 6]
初学者常见错误，可以在课程中提醒一下。

**Comment by DrTrippleJ** [comment]
这两点确实是，要不要修正一下？
@UdacityShuwenLiu

**Comment by UdacityShuwenLiu** [comment]
@DrTrippleJ 同意～
这个易错点可以以text形式加在合适的地方～～

**Comment by DrTrippleJ** [comment]
我们把你的建议加在了问题的答案框中作为一个发散，谢谢你的建议
