### ISSUE TITLE
2. Python入门 > 3. 控制流 > 7. 解决方案：条件布尔表达式 > 答案问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#355]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/0dc5b22c-4b87-4ce4-b23f-b35b0d5fa996

## 截图
![image](https://user-images.githubusercontent.com/5260728/41525694-70126d94-7314-11e8-81ba-9bf2a50d819a.png)

## 具体描述
对“复合布尔表达式”，最好给学生介绍一下编程语言对布尔表达式求值所用的技术——“短路求值”，即如果是a and b且a为False，那么将不再检查b的真假，如果a or b且a为True，那么不再检查b的真假。所有的编程语言都这么干

**Comment by DrTrippleJ** [comment]
已经添加上了，谢谢你的建议
