### ISSUE TITLE
2. Python入门 > 3. 控制流 > 18. 练习：Zip 和 Enumerate > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#356]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/f04a1bda-b2cd-420c-a25d-6e719a268c32

## 截图
![image](https://user-images.githubusercontent.com/5260728/41593837-ebdde5a4-73f3-11e8-8f1f-dfb43cb896e5.png)

## 具体描述
“练习：将列表组合成字典”翻译有误，应该把“字段”改成“字典”

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
