### ISSUE TITLE
2. Python入门 > 3. 控制流 > 21. 练习：列表推导式 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#357]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/be839dbf-f02a-4a51-b708-8e54f4b4f7e6

## 截图
![image](https://user-images.githubusercontent.com/5260728/41593937-442ecc28-73f4-11e8-8c55-672c9e8bd341.png)

## 具体描述
这里的翻译，容易让人误解是要求1-20里所有能整除3的“3的倍数”

**Comment by sylviasun916** [comment]
谢谢反馈，已修改为 ： 其中包含前 20 个 能整除 3 的整数。

**Comment by sylviasun916** [comment]
好的 谢谢指正 已修改为 “能够计算出 1 - 20 这 20 个整数中分别乘以 3 之后的结果。“ 已即时显示在教室中 。

再次谢谢指正！
