### ISSUE TITLE
2. Python入门 > 5. 脚本编写 > 29. 总结 > 跳转问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#358]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/54b598b3-4c5a-4863-aa0d-592d47f1cd8f

## 截图
![image](https://user-images.githubusercontent.com/5260728/41691850-7f1fbcb6-752f-11e8-8106-f7665915d770.png)

![image](https://user-images.githubusercontent.com/5260728/41691883-a5248590-752f-11e8-9605-ffc3b146eeb1.png)

## 具体描述
点击“提交并继续”后，并没有跳到下一课Anaconda，而是跳到第3部分去了，只有第一次点击出现这个问题，再次点击后又正常地跳到下一课Anaconda（不可复现）

**Comment by DrTrippleJ** [comment]
经过测试，没有再出现问题，谢谢你的发现！
