### ISSUE TITLE
2. Python入门 > 8. Lab：分类图像 > 3. Lab说明 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#359]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/undefined/lessons/d79396c0-8fa6-4adc-ac06-9d9649fb0525/concepts/ab7c8b0a-21c7-4d79-884d-26c371869718

## 截图
![image](https://user-images.githubusercontent.com/5260728/41751850-13f4c7f2-75f6-11e8-8cc2-9495d4850c37.png)

## 具体描述
视频29s处字幕“function tabs”错了，应该是“function stubs”，“stub”有“桩模块”的意思，这里指的是在开发一个复杂项目时，我先把大概的代码框架和函数先写出来，但具体实现放到后面再做，先有个“架子”，所以这里的英文字幕就是错误的，中文对应翻译可以为“函数桩模块”，一家之言，望斟酌，谢谢。

**Comment by leesper** [comment]
接下来的第30s也是错误的出现了tab，后面的内容应证了我说的和课程说的是一个意思——stub

**Comment by sylviasun916** [comment]
已经在数据库修改 正在部署中，谢谢反馈！ 非常专业！
