### ISSUE TITLE
3. Numpy, Pandas and Matplotlib > 3. Numpy > 9. 布尔型索引、集合运算和排序 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#360]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/1b5143bb-1d0f-49d7-a3c1-a87c5307260d/concepts/42233fd3-32a0-424d-84b3-49b96e44f1e1

## 截图
![image](https://user-images.githubusercontent.com/5260728/41825020-71465e5e-784c-11e8-916a-b8f3b810c357.png)

## 具体描述
文字资料中这里描述成“它不会对ndarray进行就地排序”就好了，其他地方出现“原地”的可以都统一改成就地，这是讲排序算法时的一种概念。

**Comment by sylviasun916** [comment]
就地比原地 更适合，感谢反馈！已即时修改，即时显示在教室里啦，谢谢！
