### ISSUE TITLE
3. Numpy, Pandas and Matplotlib > 4. Pandas > 4. 创建 Pandas Series > 文案错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#361]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/3ed4c9c1-7495-45cd-9d1f-3c8e87291d95/concepts/4be561ba-ff64-4764-bcfd-db6ccd7403b8

## 截图
![image](https://user-images.githubusercontent.com/5260728/41856482-cc1059c2-78c7-11e8-985e-3a115ff5ae04.png)

## 具体描述
文案有误，“我们先在 Python 中导入 Pandas。通常，我们使用 pd 导入 NumPy。”这里应该是“我们使用pd导入Pandas”

**Comment by sylviasun916** [comment]
已修改，即时显示在教室里，谢谢反馈！
