### ISSUE TITLE
3. Numpy, Pandas and Matplotlib > 4. Pandas > 11. 练习：操纵 DataFrame > 文案错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#362]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/undefined/lessons/3ed4c9c1-7495-45cd-9d1f-3c8e87291d95/concepts/869394af-48c8-416d-97db-d0709f52d82b

## 截图
![image](https://user-images.githubusercontent.com/5260728/41884678-ff123c0a-7926-11e8-9074-c873d61f684e.png)

## 具体描述
文案有误，应该为“上述代码返回一个只含评分为 5 的图书名称的 NumPy ndarray”

**Comment by sylviasun916** [comment]
已修改 即时显示在教室里 谢谢反馈！
