### ISSUE TITLE
3. Numpy, Pandas and Matplotlib > 4. Pandas > 14. 迷你项目：股票数据的统计信息 > 文案错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#363]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/3ed4c9c1-7495-45cd-9d1f-3c8e87291d95/concepts/ecca7776-29fe-48a9-864c-33a447f3f47a#

## 截图
![image](https://user-images.githubusercontent.com/5260728/41945468-de0dd456-79df-11e8-8fba-03c32c10e412.png)

## 具体描述
notebook第二段出现了一堆不可运行的HTML代码，似有误，可能需要修正一下，谢谢

**Comment by sylviasun916** [comment]
@UdacityShuwenLiu  可能需要麻烦看一下练习中的代码是怎么回事哦，感谢shuwen!

**Comment by UdacityShuwenLiu** [comment]
搞定 谢谢
