### ISSUE TITLE
3. Numpy, Pandas and Matplotlib > 5. Matplotlib和Seaborn（第一部分） > 11. 为离散数据选择图形 > 翻译腔太重

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#365]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/43855abb-dae5-46c7-9167-4b001dabd41e/concepts/74ab8c07-01e4-407c-8941-350a2cf49e78

## 截图
![image](https://user-images.githubusercontent.com/5260728/42007193-1a9a733a-7ab1-11e8-832a-36a4cddaa5ed.png)

## 具体描述
整篇文章的翻译腔太重，我就没怎么看懂它想表达的是什么意思，类似“虽然可以使用条形图绘制离散数字数据，但是以下对立面的理由却不充分”，实在是太拗口，无力吐槽

**Comment by UdacityShuwenLiu** [comment]
@sylviasun916 请帮忙查看一下，谢谢圆圆～

**Comment by sylviasun916** [comment]
已即时修改显示在教室内，谢谢反馈！
