### ISSUE TITLE
3. Numpy, Pandas and Matplotlib > 5. Matplotlib和Seaborn（第一部分） > 12. 描述统计学、离群值和坐标轴范围 > 翻译错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#366]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/43855abb-dae5-46c7-9167-4b001dabd41e/concepts/1523cdaa-1c53-47fd-ab3e-a31631dcacad

## 截图
![image](https://user-images.githubusercontent.com/5260728/42119500-54f782a4-7c3f-11e8-9516-31a73aa34331.png)

## 具体描述
“例如模式数量和偏态”，这里mode不能翻译成模式，这里是指直方图的“峰”，麻烦改正下

**Comment by UdacityShuwenLiu** [comment]
@sylviasun916 请帮忙查看一下，谢谢圆圆～

**Comment by sylviasun916** [comment]
已即时修改显示在教室中，感谢反馈！
