### ISSUE TITLE
3. Numpy, Pandas and Matplotlib > 5. Matplotlib和Seaborn（第一部分） > 13. 标尺和变换 > 翻译错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#367]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/43855abb-dae5-46c7-9167-4b001dabd41e/concepts/7623c273-f807-4da3-9ce4-93124bc9ce42

## 具体描述
"对于很多人来说，只有将整数的对数值转换为原始值很轻松"，这句话看不懂

**Comment by UdacityShuwenLiu** [comment]
@sylviasun916 请帮忙查看一下，谢谢圆圆～

**Comment by sylviasun916** [comment]
已修改即时显示在教室中，改为“对于很多人来说，他们只会相对娴熟地将整数的对数值转换为原始值”，谢谢反馈！
