### ISSUE TITLE
3. Numpy, Pandas and Matplotlib > 5. Matplotlib和Seaborn（第二部分） > 5. 小提琴图 > 视频无字幕

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#368]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/0491d74e-dcd8-4700-a971-a7f1b0a26ddb/concepts/1dca3bcb-d2d4-44c2-b88e-ecea98402349

## 截图
![image](https://user-images.githubusercontent.com/5260728/42130107-1c466312-7d0c-11e8-92a1-fc1a84770abf.png)

## 具体描述
第一个视频，没有字幕，右下角的“CC"点开后是空的

**Comment by sylviasun916** [comment]
已重新更新字幕在教室中啦，之前丢失是因为总部近期有重新上传过该视频，导致原字幕丢失。 

现在已即时显示啦，谢谢反馈！
