### ISSUE TITLE
4. 线性代数基础 > 2. 向量 > 6. 大小和方向 > 翻译错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#369]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/58c729f7-3b80-4259-abeb-327e1ec1d695

## 截图
![image](https://user-images.githubusercontent.com/5260728/42354168-9c432e6c-80f7-11e8-836f-172a9b47d2ab.png)

## 具体描述
“将度数转换为半径”翻译有误，应该是“将度数转换为弧度”

**Comment by DrTrippleJ** [comment]
已经解决，谢谢
