### ISSUE TITLE
4. 线性代数基础 > 3. 线性组合 > 5. 线性相关性 > 文案错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#370]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/7944df46-7a24-45ac-a27d-ac6620667108/concepts/fd7ae294-9671-4f53-88ef-230ec6913302

## 截图
![image](https://user-images.githubusercontent.com/5260728/42405439-347d1028-81c8-11e8-9c09-d8953bfd012f.png)

## 具体描述
我认为这里v1和v3是线性无关的集合，它们中的任意一个无法用另一个乘以标量表示。

**Comment by DrTrippleJ** [comment]
已经解决，谢谢
