### ISSUE TITLE
4. 线性代数基础 > 3. 线性组合 > 6. 求解简化的方程组 > 文案错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#371]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/7944df46-7a24-45ac-a27d-ac6620667108/concepts/852f9480-8058-4f61-bdc3-194408b72d92

## 截图
![image](https://user-images.githubusercontent.com/5260728/42405499-7adae8fa-81c9-11e8-8e0f-4142de0a1c31.png)

## 具体描述
文案所介绍的三种解法得到的都是a=-0.5 b=-4，怎么结论又变成a=-0.2 b=-4了呢？还有明明两个系数求解出来都是负的，那么文案里的“一个系数为正，另一个为负”是不是有误，请确认，谢谢。

**Comment by DrTrippleJ** [comment]
已修改，谢谢
