### ISSUE TITLE
P3 线性代数-课程三-2-未翻译

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#372]
## 课程导航+地址
例子：P3 线性代数-课程三-2-未翻译
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/872aea9e-6e18-4104-8358-4e4d96d4ae45/concepts/d3f66379-e893-41b2-8b64-c9b6c1dda9db#
## 截图
![default](https://user-images.githubusercontent.com/34020359/42435024-de07c762-8387-11e8-8a9b-39c55a4ff3b5.png)

7-10日404
![image](https://user-images.githubusercontent.com/34020359/42492447-b0b3c4cc-844b-11e8-9f1e-439d7c6a994b.png)

## 具体描述
未翻译

**Comment by DrTrippleJ** [comment]
已解决，谢谢
