### ISSUE TITLE
4. 线性代数基础 > 7. 线性映射Lab > 2. 可视化矩阵乘法 > notebook文案错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#373]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/872aea9e-6e18-4104-8358-4e4d96d4ae45/concepts/d3f66379-e893-41b2-8b64-c9b6c1dda9db#

## 截图
![image](https://user-images.githubusercontent.com/5260728/42545668-e5cfe6f4-84eb-11e8-8ab4-1dbb3a7438f8.png)

## 具体描述
这里明显不是Python代码，是想提供练习的答案吧？但是最后给出的是None，需要修改一下

**Comment by DrTrippleJ** [comment]
已修改，谢谢
