### ISSUE TITLE
4. 线性代数基础 > 7. 线性映射Lab > 3. 矩阵乘法Lab > notebook上传错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#374]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/872aea9e-6e18-4104-8358-4e4d96d4ae45/concepts/84850c41-5a08-4ce7-9a6e-4299c2b0f045#

## 截图
![image](https://user-images.githubusercontent.com/5260728/42605911-1b492f40-85ad-11e8-97fe-6593f41ebb02.png)

## 具体描述
“可视化矩阵乘法”和“矩阵乘法Lab”内容重复了，根据最后一节“线性映射Lab解决方案”给出的视频，矩阵乘法Lab应该介绍的主题是“通过矩阵乘法进行货币换算”，但估计是上传错误，现在两个地方给出的学习内容一模一样，请重传一份，谢谢。

**Comment by DrTrippleJ** [comment]
已经解决，谢谢你的细心
