### ISSUE TITLE
python入门 》 第八节，LAB 》 第13小节 》 字幕-无字幕问题 -严重

### ISSUE THREAD

**Issue by wilow89** [udacity/aipnd-issues-zh#375]
## 课程导航+地址
python入门 》 第八节，LAB 》 第13小节 》 字幕-无字幕问题 -严重
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/f8c19d5d-077d-4a0d-89db-08b8fd9fbcd2/lessons/d79396c0-8fa6-4adc-ac06-9d9649fb0525/concepts/356e8d82-0ba2-49d4-b846-867a343764e7

## 截图
![image](https://user-images.githubusercontent.com/34020359/42923561-a2646ade-8b58-11e8-9492-3bd2d30025c6.png)

## 具体描述
无字幕

**Comment by DrTrippleJ** [comment]
这个问题我们现在还不好处理，抱歉，所以我们现在只能先加上label

**Comment by sylviasun916** [comment]
fixed and thanks!
