### ISSUE TITLE
4.线性代数基础 >2 向量 > 2.什么是向量（第二部分）>翻译不通顺，不符合中国人说话习惯

### ISSUE THREAD

**Issue by TieDanCuihua** [udacity/aipnd-issues-zh#379]
## 课程导航+地址
线性代数基础 > 向量 > 什么事向量（第二部分） >https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/7f969ff5-07bb-48dd-9cc8-1be463f4442d

## 截图
<img width="1212" alt="demo" src="">
![image](https://user-images.githubusercontent.com/41666768/43623254-e6e73554-9712-11e8-9002-c4cba4697105.png)

## 具体描述
“不知为何，上传图片很困难，很少能成功”
0:22-0:27处的翻译是完全照搬英文语句翻译的，没有按照中国人的说话习惯合理调整语序。
建议翻译改为：当我想把二维空间看做一个整体时，我会把这些刻度延伸出去，形成网格线。在接下来的视频中我会经常这么做，不过现在网格线有点碍事。

**Comment by DrTrippleJ** [comment]
这个问题我觉得不仅要考虑符合语句翻译与习惯，也要考虑底下的中文字幕是否与视频想搭配，毕竟不是有很多人愿意打开英文字幕的，我觉得这里不碍理解，所以决定这里不进行修改，并close。如果你有疑问，可以重新打开，我们来进行讨论。谢谢你的建议
