### ISSUE TITLE
2. Python入门 > 2. 数据类型和运算符 > 1. 简介 > 视频中文字幕翻译问题

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#381]
## 课程导航+地址
2. Python入门 > 2. 数据类型和运算符 > 1. 简介 > 视频1m12s中文字幕翻译问题

## 截图

![image](https://user-images.githubusercontent.com/7189743/43669201-d694376e-97b3-11e8-9fb7-013b60287513.png)

## 具体描述
视频1m12s字幕问题：
1、依然去掉
2、后半句“但是我们看不到结果“跑到下一句的翻译里面去了

**Comment by DrTrippleJ** [comment]
这里我感觉其实还行，那个依然对应的是still，所以这里就先不做修改了并close了。如果你有疑问可以重新open。谢谢你的建议
