### ISSUE TITLE
2. Python入门 > 2. 数据类型和运算符 > 5. 练习：变量和赋值运算符 > 测试答案验证不正确

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#382]
## 课程导航+地址
2. Python入门 > 2. 数据类型和运算符 > 1. 练习：变量和赋值运算符 > 测试答案验证不正确

## 截图
![image](https://user-images.githubusercontent.com/7189743/43669690-80a2bad4-97b7-11e8-8549-a2d8e26eea2d.png)

## 具体描述
6229为正确答案，提交后提示错误

**Comment by DrTrippleJ** [comment]
已修改，谢谢
