### ISSUE TITLE
2. Python入门 > 2. 数据类型和运算符 > 7. 整数和浮点数 > 第一个视频2m42s中文字幕

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#383]
## 课程导航+地址
2. Python入门 > 2. 数据类型和运算符 > 7. 整数和浮点数
## 截图
![image](https://user-images.githubusercontent.com/7189743/43669797-632d81e0-97b8-11e8-8da3-d1eefe29018d.png)

## 具体描述
第一个视频2m42s中文字幕，应该改为：不能将人数统计成0.47人

**Comment by DrTrippleJ** [comment]
已修改。突然想着原视频的那个翻译的数会不会是动词。。。。。

**Comment by huanghyw** [comment]
你这么一说还真有可能，汉语真是博大精深啊。。。
