### ISSUE TITLE
2. Python入门 > 2. 数据类型和运算符 > 24. 练习：集合 > 练习：将列表转换为集合提交答案后排版乱了

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#384]
## 课程导航+地址
2. Python入门 > 2. 数据类型和运算符 > 24. 练习：集合 > 第一个问题提交答案后排版乱了
## 截图
![image](https://user-images.githubusercontent.com/7189743/43669935-8ba1586c-97b9-11e8-94b3-5a330aabaf8e.png)

## 具体描述
第一个问题提交答案后排版乱了

**Comment by DrTrippleJ** [comment]
已修改，谢谢，另希望下次附上直接网址
