### ISSUE TITLE
2. Python入门 > 2. 数据类型和运算符 > 1. 简介 > 视频中文字幕翻译问题

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#385]
## 课程导航+地址
Python入门 > 数据类型和运算符 > [1.简介](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/2cc7d900-a68a-4565-b98e-41ba13a3ac88)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/43671417-4ef91d10-97cc-11e8-9636-b0d32f556756.png">

## 具体描述
视频17处字幕"请按照自己的时间安排理解后面介绍的每个概念"，需改为"花些时间理解后面介绍的每个概念"

**Comment by DrTrippleJ** [comment]
已修正，谢谢

**Comment by sylviasun916** [comment]
已修改 感谢反馈
