### ISSUE TITLE
2. Python入门 > 2. 数据类型和运算符 > 2. 算术运算符 > 视频中文字幕翻译问题

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#386]
## 课程导航+地址
例子：Python入门 > 数据类型和运算符 > [2.算术运算符](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/861222b2-49d8-40c5-8e6c-9880f0044504)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/43671523-4014eec6-97ce-11e8-980e-44d08c700dab.png">
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/43671526-4dcbc47c-97ce-11e8-8a67-6a5375bc1880.png">

## 具体描述
视频1min51s处字幕"取模运算"，是否需改为"取余预算"？
下面文本注释部分为 "取余运算"，是否给出链接解释 取模运算 与 取余运算 比较的链接

**Comment by DrTrippleJ** [comment]
这里是下方文档错误，谢谢你的发现，并且我们也添加了备注
