### ISSUE TITLE
5. 神经网络简介>9. 感知器技巧 - 计算机如何“学习”分类？

### ISSUE THREAD

**Issue by aimuch** [udacity/aipnd-issues-zh#387]
## 截图
<img width="1212" alt="demo" src="
![image](https://user-images.githubusercontent.com/17581911/43671608-c2f4cf9a-97cf-11e8-8d52-e67b19bcbc14.png)
">

## 具体描述
最后一个视频，YouTube源播放，2:54处woola删除

**Comment by sylviasun916** [comment]
不太确定这是什么问题？

**Comment by DrTrippleJ** [comment]
@sylviasun916 应该是youtube源的视频字幕在2:54处多出现了一个woola，我去确认一下去

**Comment by DrTrippleJ** [comment]
@sylviasun916 
![image](https://user-images.githubusercontent.com/33549539/46127832-71689e80-c264-11e8-9ad6-f4ace64856ad.png)

是在2:52秒处多句子前面多出现了一个woola，但是英文的对应字幕和翻译的不一样
![image](https://user-images.githubusercontent.com/33549539/46127915-9c52f280-c264-11e8-80c3-bd0f1f38bdaa.png)
应该是翻译错误了

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
