### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#388]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程1：简介 > [3. 课程讲师]https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/8bdd3743-dd67-4d35-b2b9-7b533645331b/concepts/undefined

## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
Grant Sanderson图片标题为斜体；
Ortal图片无标题；
Jennifer Staab照片不显示，标题为正体。

**Comment by DrTrippleJ** [comment]
已修改，谢谢
