### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#389]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程1：简介 > [5. 处理方法]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/8bdd3743-dd67-4d35-b2b9-7b533645331b/concepts/ae23ec3b-86b3-40b7-99ca-7bb0ae0af031
## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43671838-ca5539e2-97d3-11e8-8a2a-ed23511b7add.png)

## 具体描述
正确答案和错误答案下方图片显示空白，（不知是否网络问题）

**Comment by DrTrippleJ** [comment]
应该是网络问题，我这里显示正常，谢谢
