### ISSUE TITLE
2. Python入门 > 2. 数据类型和运算符 > 7. 整数和浮点数 > 视频英文未翻译

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#390]
## 课程导航+地址
例子：Python入门 > 数据类型和运算符 > [7.整数和浮点数](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/0056decd-35dc-41d0-9d58-22b3752fb20f)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/43671848-fbc7c346-97d3-11e8-8482-2d0360d29a6b.png">

## 具体描述
视频9s处字幕"other types of numbers do exist in Python"，未翻译

**Comment by sylviasun916** [comment]
fixed and thanks!
