### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#391]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程2：向量 > [4. 向量-数学定义]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/0393209e-3dbf-45f4-aa81-6e38b5b66a08
## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43671988-59b03dd2-97d7-11e8-9a28-1d9809d59342.png)

## 具体描述
“此处”链接无法打开（墙内，墙外均打不开）

**Comment by DrTrippleJ** [comment]
尝试过了，墙内墙外均可打开，可能是网络问题。谢谢你的反馈
