### ISSUE TITLE
链接需翻墙打开

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#392]
## 课程导航+地址

人工智能编程基础 > 线性代数基础 > 课程2：向量 > [6. 大小和方向]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/58c729f7-3b80-4259-abeb-327e1ec1d695

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43672036-3fb4de00-97d8-11e8-9942-8b607d212e81.png)

## 具体描述
“勾股定理”的链接为英文维基百科，需要翻墙打开。

**Comment by DrTrippleJ** [comment]
英文wiki应该是不用翻墙的，中文才需要，可能因为我这是校园网？
@UdacityShuwenLiu 以后出现这种问题我们能换成百度百科吗？
