### ISSUE TITLE
链接打开失效

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#393]
## 课程导航+地址

人工智能编程基础 > 线性代数基础 > 课程2：向量 > [6. 大小和方向]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/58c729f7-3b80-4259-abeb-327e1ec1d695

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43672036-3fb4de00-97d8-11e8-9942-8b607d212e81.png)
![image](https://user-images.githubusercontent.com/38323732/43672069-adc2b4da-97d8-11e8-9227-cf1f7e47d299.png)

## 具体描述
链接打开为空白页面，不知是否我的网络问题。

**Comment by DrTrippleJ** [comment]
可能是网络问题，我这里可以打开

**Comment by DrTrippleJ** [comment]
@UdacityShuwenLiu 这种国内可能时好时坏的网站需要进行替换吗？
