### ISSUE TITLE
翻译建议：专业术语

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#394]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程2：向量 > [8. 场中的运算]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/83b857a9-9ea7-45d6-9f63-49c818a86a5a

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43672127-09577fe6-97da-11e8-9f0d-cd9ff4f683d4.png)

## 具体描述
国内的线性代数课程里，一般称为：
结合律
交换律
分配律
（个人观点）

**Comment by DrTrippleJ** [comment]
谢谢，这里原来应该是为了与后面统一，不过有单位元和逆元这种翻译，所以此处修改为律会贴切一些
