### ISSUE TITLE
5. 神经网络介绍>15.softmax函数>0:23处翻译怪怪的

### ISSUE THREAD

**Issue by aimuch** [udacity/aipnd-issues-zh#395]
## 截图
<img width="1212" alt="demo" src="
![image](https://user-images.githubusercontent.com/17581911/43672194-88266070-97db-11e8-8f38-8cf4c8908b08.png)
">

## 具体描述
0:23处翻译怪怪的(YouTube源)

**Comment by DrTrippleJ** [comment]
好的，不过如果能在国内环境下观看就最好了，因为我们的大部分学员应该都还是会在国内环境下观看，谢谢

**Comment by DrTrippleJ** [comment]
@UdacityShuwenLiu 
字幕翻译问题应该怎么处理呢？

**Comment by sylviasun916** [comment]
fixed and thanks
