### ISSUE TITLE
文本标点错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#396]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程3：线性组合 > [3. 线性组合和张成]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/7944df46-7a24-45ac-a27d-ac6620667108/concepts/29d25468-2ac0-4a9f-ac21-962c4765f498
## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43672700-3729e8c6-97e6-11e8-89ee-b428acbb19bf.png)

## 具体描述
结尾缺一个句号

**Comment by DrTrippleJ** [comment]
谢谢，已修改
