### ISSUE TITLE
文本错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#397]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程3： 线性组合> [5. 线性相关性]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/7944df46-7a24-45ac-a27d-ac6620667108/concepts/fd7ae294-9671-4f53-88ef-230ec6913302

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43672722-abb4ec72-97e6-11e8-914a-cb207025858a.png)

## 具体描述
由于v1=【1，2，3】，v3=【8，8，8】两者不相关。
“线性相关的集合”，应修改为“线性不相关的集合”。

**Comment by DrTrippleJ** [comment]
谢谢，已修改
