### ISSUE TITLE
文本翻译错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#398]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程3：线性组合 > [6. 求解简化的方程组]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/7944df46-7a24-45ac-a27d-ac6620667108/concepts/852f9480-8058-4f61-bdc3-194408b72d92
## 截图
![image](https://user-images.githubusercontent.com/38323732/43672772-74fafdd8-97e7-11e8-863f-e7f3a912b021.png)

## 具体描述
“你将详细了解n个线性方程组“，应修改为”你将详细了解含有n个线性方程的方程组'

**Comment by DrTrippleJ** [comment]
已修改，谢谢
