### ISSUE TITLE
文本翻译纠正

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#400]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程4：线性变换和矩阵 > [2. 矩阵加法]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/d9334d0c-1a33-4913-8b21-a643a8d7a2a0/concepts/222a0172-4a59-452d-8567-024f07a7662b
## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43672875-0ca4b01e-97ea-11e8-888b-e987c139f2eb.png)

## 具体描述
“维度相符”，应改为“维度相同”

**Comment by DrTrippleJ** [comment]
谢谢，已修改
