### ISSUE TITLE
文本翻译不妥当

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#401]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程4：线性变换和矩阵 > [5. 方形矩阵和乘法]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/d9334d0c-1a33-4913-8b21-a643a8d7a2a0/concepts/b996e37a-d316-4c26-afe7-14e93b68b521
## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43672901-e6e01dae-97ea-11e8-87e5-718405872b00.png)

## 具体描述
“条目AB”，不是数学概念，建议修改“矩阵积AB”

**Comment by DrTrippleJ** [comment]
已修改，谢谢
