### ISSUE TITLE
文本翻译纠正

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#402]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程4：线性变换和矩阵 > [6. 方形矩阵乘法练习]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/d9334d0c-1a33-4913-8b21-a643a8d7a2a0/concepts/56e34aae-1031-411b-b796-cd9c40f4e652
## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43672915-64a7c048-97eb-11e8-983e-6c09e534c1cc.png)

## 具体描述
不可交换实际上就是不满足交换律。
建议将“我们称之为不可交换。这是一个有趣的现象，标量乘法肯定是可交换的。”
修改为“我们称之为不满足交换律。这是一个有趣的现象，标量乘法肯定是满足交换律的。”

如果同意我的修改方案。在[7. 矩阵乘法·一般情况]内也有需要修改的文本。

**Comment by DrTrippleJ** [comment]
提及的文本已修改，谢谢你的建议
