### ISSUE TITLE
markdown文本错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#404]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程5：向量lib > [1. 绘制向量]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/1d0cd6f3-41eb-49c0-b1bb-3746eced5a97/concepts/1f9246d1-4879-4bca-a2a8-6a9629347795
## 截图
“### 向量相加”三级标题下。

## 具体描述
"我们在下图中显示了将向量 $\vec{w}$ 加到向量 $\vec{v}$ 上的过程。"应修改为：
“我们在下图中显示了将向量 $\vec{w}$ 加到向量 $\vec{v}$ 上的过程。”

**Comment by DrTrippleJ** [comment]
好的，我们已经修改，谢谢
