### ISSUE TITLE
markdown文本错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#405]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程5：向量lib > [1. 绘制向量]

## 截图

倒数第二个三级标题“### 将两个向量相加的解决方案”下

## 具体描述
请点击此处查看解决方案，的“此处”链接打不开（错误代码404）

**Comment by DrTrippleJ** [comment]
好的，我们已经修正，谢谢
