### ISSUE TITLE
链接打开后加载错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#406]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程5：向量lib > [2. 向量lib解决方案]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/1d0cd6f3-41eb-49c0-b1bb-3746eced5a97/concepts/de0ac86d-1f6e-47e7-9193-de6ad97a36b0

## 具体描述
向量 Lab Jupyter Notebook
向量 Lab 解决方案 Jupyter Notebook
两个链接均无法打开，不知是否网络问题？

**Comment by DrTrippleJ** [comment]
应该是网络问题，本身连接是github连接，应该不需要翻墙，谢谢你的建议
