### ISSUE TITLE
文本格式错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#407]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程1：简介 > [4. 课程结构]

https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/8bdd3743-dd67-4d35-b2b9-7b533645331b/concepts/5923dbfa-97ad-4a71-96c9-8660a61df590
## 具体描述
“视频- 以直观形式强调线性代数的精彩之处。_ 讲师：Grant。_”内，“讲师：Grant。”前后多了两个“_”，并且字体是正体，而不是斜体。

**Comment by DrTrippleJ** [comment]
好的，我们已做修改，谢谢
