### ISSUE TITLE
数学概念翻译不准确

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#409]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程2：向量 > [8. 场中的运算]

https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/83b857a9-9ea7-45d6-9f63-49c818a86a5a

## 截图
（无法粘贴或上传截图）

## 具体描述
该页面所有的“场Rn”应修改为“实数域Rn”更为妥当。
“场公理”应修改为“实数域公理”

**Comment by DrTrippleJ** [comment]
没错，应该这么修改，谢谢
