### ISSUE TITLE
翻译不准确

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#410]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程2：向量 > [8. 场中的运算]

https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/83b857a9-9ea7-45d6-9f63-49c818a86a5a

## 截图
（无法粘贴或上传截图）

## 具体描述
“它是零向量：”应修改为“它是由元素0组成的向量：”

“它是一向量：”应修改为“它是由元素1组成的向量：”

**Comment by DrTrippleJ** [comment]
这里原本是one element和zero element，指代实数域公理中的加法单位元和乘法单位元，我咨询一下看看国内有么有确切的翻译

**Comment by DrTrippleJ** [comment]
没有找到对于这个地方的确切翻译，因此采用你的翻译并把前面的0和1加粗以表示向量，谢谢你的细心
