### ISSUE TITLE
数学概念翻译不准

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#411]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程2：向量 > [9. 向量加法]

https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/fba2a16b-ed8b-4a00-a064-17a007e28b19

## 截图
（无法粘贴或上传截图）

## 具体描述
“将位于相同的场”应修改为：
“将位于相同的实数域”

**Comment by DrTrippleJ** [comment]
已修改，谢谢
