### ISSUE TITLE
文本翻译不准确

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#412]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程2：向量 > [10. 向量-练习2]

https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/d4aba2ac-8f18-4151-affa-41e69ef78807/lessons/1f834b40-6d19-4add-a193-6f4a419821ac/concepts/1f15b4ff-06c6-43d0-a21a-a6cfa0fcfbfe

## 截图
（无法粘贴或上传截图）

## 具体描述
线性代数没有2D,3D的说法，一般都是表述为二维空间，三维空间。

“这道练习侧重于2D空间，即位于场R2  中。”应修改为：
“这道练习侧重于二维空间，即位于实数域R2  中。”

**Comment by DrTrippleJ** [comment]
已修改，谢谢
