### ISSUE TITLE
5.神经网络>2.训练神经网络>5正则化

### ISSUE THREAD

**Issue by aimuch** [udacity/aipnd-issues-zh#414]
## 截图
<img width="1212" alt="demo" src="图片地址
![image](https://user-images.githubusercontent.com/17581911/43682142-eef5b7d0-989c-11e8-986e-2b86f6ed5299.png)
">

## 具体描述
提交答案后，应该提示【若用YouTube源会有解答窗口弹出】

**Comment by DrTrippleJ** [comment]
在题目下方添加了注释，谢谢你的建议
