### ISSUE TITLE
缺一个句号

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#420]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程7：线性映射lab > [3. 矩阵乘法lab]

https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/872aea9e-6e18-4104-8358-4e4d96d4ae45/concepts/84850c41-5a08-4ce7-9a6e-4299c2b0f045
## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/43766955-69ffad44-9a66-11e8-8c3a-ec6fe819f26c.png)

## 具体描述
缺一个句号~

**Comment by DrTrippleJ** [comment]
谢谢你的细心~
