### ISSUE TITLE
文本格式错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#421]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程7：线性映射lab > [3. 矩阵乘法lab]

## 截图
![image](https://user-images.githubusercontent.com/38323732/43767228-20a4bb7a-9a67-11e8-9406-46756061285f.png)

## 具体描述
原文本大概是想变为斜体，但是只有一个“_”，所以，显示出来就多了一个“_”

**Comment by DrTrippleJ** [comment]
已经修正了，谢谢~
