### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 2. 分类问题 > 提交答案后视频无法显示

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#422]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 >  [2. 分类问题]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/501ce6c5-9b80-4536-8754-f7da607fc40d#
## 截图
![image](https://user-images.githubusercontent.com/41724066/43769592-ad5ee5a4-9a6c-11e8-9350-470e34a67eb6.png)

## 具体描述
全局模式下，提交答案后的弹框页面无法弹出解答视频，也无其他提示说明。

**Comment by DrTrippleJ** [comment]
我这里是可以的，可能是网络问题
![image](https://user-images.githubusercontent.com/33549539/43786294-e2c7685a-9a9a-11e8-91bf-2e24be5b3051.png)
