### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 5.更高维度的界线

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#424]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 > [5.更高维度的界线]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/3a0e2972-89dc-4b08-826a-1011b9b554ac

## 截图
![image](https://user-images.githubusercontent.com/41724066/43771074-a2dde676-9a70-11e8-844e-f3dc70a59276.png)

## 具体描述
1、备注的修正有问题。
2、视频1:04处的出现的图标上，标注的“<--- n columns -->" 箭头包含的范围有误。
根据教学视频的讲解的意思，应该是：”如果有很多列呢？譬如有n列”。图标中最后一列 pass？ 是预测结果列，不是输入条件列，所以不应该包含在 n columns 的箭头范围内。
同理，也不应该理解成备注的修正描述那样。

**Comment by DrTrippleJ** [comment]
这个视频内容我们会再做讨论，谢谢你的细心

**Comment by DrTrippleJ** [comment]
@UdacityShuwenLiu 淑雯，这个地方我看了一下，确实是视频里面标注出了问题，底下右边那个箭头应该不包括最后一个竖行的，所以咱们的备注得修改一下。我建议修改为“视频中表格下方的箭头囊括范围应不包含最后一列”，你觉得可以吗？

**Comment by UdacityShuwenLiu** [comment]
已修复，感谢反馈！

**Comment by UdacityShuwenLiu** [comment]
已修复，感谢反馈！
