### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > [9.感知器技巧] > 文字表达不当

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#425]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 > [9.感知器技巧]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/8ea20904-0215-4e44-afa9-bb5a720bd028

## 截图
![default](https://user-images.githubusercontent.com/41724066/43771940-40434af8-9a73-11e8-9623-cec4ed3f01d7.png)

## 具体描述
文字表述前后矛盾，上一段红框内说”计算机无法自己构建这些感知器函数“，下一段红框内又说”视频将展示计算机如何自己构建感知器函数“。
关键点没有表达清楚。

**Comment by DrTrippleJ** [comment]
翻译的锅，文本已修正，你这下去读就懂了~
