### ISSUE TITLE
人工智能编程基础 》 5.神经网络 》 4.线性界线 

### ISSUE THREAD

**Issue by TaylorHuang2017** [udacity/aipnd-issues-zh#426]
## 课程导航+地址
人工智能编程基础 》 5.神经网络 》 4.线性界线 
中英文字幕的位置颠倒了

## 截图
<img width="1212" alt="demo" src="https://github.com/TaylorHuang2017/MachineLearning_boston_housing/blob/master/2018-08-07_185645.jpg?raw=true">

## 具体描述
视频1：47处中英文字幕的位置反了，应改为英文在上，中文在下。

**Comment by sylviasun916** [comment]
工程问题，暂时无法解决
