### ISSUE TITLE
5 神经网络 》6.对数概率感知器

### ISSUE THREAD

**Issue by TaylorHuang2017** [udacity/aipnd-issues-zh#427]
## 课程导航+地址
5 神经网络 》6.对数概率感知器

https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/6ba9c9eb-2e36-4b03-9bcc-01e71260a024 

## 截图
<img width="1212" alt="demo" src="https://github.com/TaylorHuang2017/MachineLearning_boston_housing/blob/master/2018-08-07_192706.jpg?raw=true">

## 具体描述
视频2分58秒s处字幕“结算”？用词欠妥（可能笔误），需改为“计算”

**Comment by DrTrippleJ** [comment]
已修改，谢谢
