### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#429]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程7：线性映射lab > [3. 矩阵乘法lab]

## 具体描述
IN[2]:Inputs Vector:
IN[3]不知道存在的意义是什么?是不是之前有人做过了？

类似这种问题，是否还要提交issue

**Comment by DrTrippleJ** [comment]
凡是你觉得可以提交的，都提交

evan zhang <notifications@github.com>于2018年8月7日 周二下午7:56写道：

**Comment by DrTrippleJ** [comment]
已经修正了，谢谢你的大发现
