### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 【9.感知器技巧】 > 中文字幕中的方程式表达有歧义

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#430]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 > 【9.感知器技巧】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/8ea20904-0215-4e44-afa9-bb5a720bd028

## 截图
![default](https://user-images.githubusercontent.com/41724066/43774594-34b0a268-9a7c-11e8-80d9-1585e51b1ff2.png)

## 具体描述
视频8s处字幕3x1 + 4x2 - 10，需改为其中2个x后面的1、2分别为x的角标，要么将角标数字做右下处理，要不把中文字幕中的线性方程式，表达为：3*X1 + 4*X2 - 10
以此尽量减少歧义的产生，现在会误认为方程式中3x1 的意思是：3和1相乘。

**Comment by sylviasun916** [comment]
已修改 感谢反馈
