### ISSUE TITLE
5.神经网络 》7. 为何是神经网络

### ISSUE THREAD

**Issue by TaylorHuang2017** [udacity/aipnd-issues-zh#432]
## 课程导航+地址
5.神经网络 》7. 为何是神经网络

https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/a3b18b18-8496-4775-af48-921ab35bd306

## 截图
<img width="1212" alt="demo" src="https://github.com/TaylorHuang2017/MachineLearning_boston_housing/blob/master/2018-08-07_201347.jpg?raw=true">

## 具体描述
视频28s处字幕“神经冲动”，用词欠妥，需改为“神经脉冲”，更符合中文的语言习惯

**Comment by DrTrippleJ** [comment]
谢谢你的建议
