### ISSUE TITLE
图片显示错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#433]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程 8: 神经网络中的线性代数 > [1. 课程讲师]

https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4478e0aa-e136-44eb-a81e-c158ad213487/modules/f8ebb5d5-6be0-4287-bbec-fb84dd3da8e3/lessons/9030e3b5-5e66-4e2b-97a3-351758b5f1f6/concepts/d4e4f5c9-0c55-4e6c-9f6d-1fec57cfb218
## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
只有导师姓名，未显示导师照片

**Comment by DrTrippleJ** [comment]
![image](https://user-images.githubusercontent.com/33549539/43784298-5822faa6-9a96-11e8-8c4b-118dda6fc6ef.png)
这个真的是网路缘故(｡í _ ì｡)
