### ISSUE TITLE
翻译不准确

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#434]
## 课程导航+地址
人工智能编程基础 > 线性代数基础 > 课程 8: 神经网络中的线性代数 > [2. 课程简介]

## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
但是在这节课我们将重点讲解在神经网络中的运用！修改为：
但是在这节课我们将重点讲解其在神经网络中的运用！

该纳米学位课程的下一节课将阐述神经网络，修改为：
该纳米学位课程的下一节课将阐述神经网络的知识。

下方貌似有一个图片，但显示为空白。

**Comment by DrTrippleJ** [comment]
文字内容已修改，图片加载不出来可能是网络缘故
