### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 【10.感知器算法】 > 视频动画效果和讲解内容没对上

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#437]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 > 【10.感知器算法】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/dc837952-c0d8-43fc-921c-f1ffe316c795

## 截图

![default](https://user-images.githubusercontent.com/41724066/43776166-9625b830-9a81-11e8-9c5c-921433e7169b.png)

## 具体描述
1、视频40s处出现的右侧点【i am good！】动画效果的出现偏慢。应该在直线第一次移动到位后就出现
2、还是那个问题，时长2分14秒的教学视频，其中30s都在将红蓝区域哪些点分类正确，哪些分类错误。我只想了解算法的推算过程或更多的代码编写教程，这两个才是我打开【感知算法】内心期待学习并了解的核心内容啊

**Comment by DrTrippleJ** [comment]
谢谢你的建议，视频我们无法做更改，因为是美国本部制作的，我们会考虑以文字形式添加你说的内容的
