### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 【10.感知器算法】 >  python代码提交后没有直观的结果显示

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#439]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 > 【10.感知器算法】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/dc837952-c0d8-43fc-921c-f1ffe316c795

## 截图
![default](https://user-images.githubusercontent.com/41724066/43776629-038f11cc-9a83-11e8-9b55-ed88cbf6b836.png)

## 具体描述
1、代码编译正确，希望能提供直观的代码运行结果，譬如画出的那条线是长成啥样的
2、不太明白最后一个自定义函数trainPerceptronAlgorithm，其中 x_min， y_min， y_max没有用到
3、不太明白这里data.csv的存在意义，好像没用到的样子
4、希望除了简单提供标准代码答案外，能对解题过程做更多的解释和教学。这种关键环节，直接给个答案让学员自行理解，不科学...

**Comment by DrTrippleJ** [comment]
这个地方相信你往后坐也发现了，在后面一节我们有更详细的代码与可视化，这里应该是改课程时遗留下来的东西，我们会商讨怎么处理的，谢谢你的建议，我们欢迎你对课程内容提出自己的观点~
