### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 【13.Logistic误差函数与梯度下降】 > 关于翻译“罚值”

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#441]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 > 【13.Logistic误差函数与梯度下降】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/5e1f6c71-6c75-4bb2-98a9-ee40c0eb3472

## 截图
![image](https://user-images.githubusercontent.com/41724066/43813869-3823c050-9afa-11e8-8fbd-9b4ba7ff272b.png)

## 具体描述
视频3：45处字幕“分配大的罚值”，建议修改为：“分配大的惩罚值”，后面使用罚值的地方做同样修改。
这里的罚值不知道是不是从，惩罚函数中所值的那个定义，使用相对比较冷门。在只看中文字幕的情况下，很容易想当然的把“罚值”理解成“阀值”的错别字。
最好能在扩展阅读中，给大家备注一些关于“惩罚值”出处的相关资料。

**Comment by DrTrippleJ** [comment]
我们在视频下方给了翻译备注，但惩罚值的概念的话，觉得这里更改了翻译以后应该会好理解很多，并且也只是字面上的意思，就是会给分类错误的点一个比较大的惩罚而已，所以暂时不添加更多的资料了（其实是我也没找到），后面课程优化时我们会再做讨论，这个问题就先close了
