### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 【15.softmax误差函数】 > 翻译问题

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#442]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 > 【15.softmax误差函数】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/9e1364a8-e8b4-4eac-be12-4d44a139f721

## 截图
![image](https://user-images.githubusercontent.com/41724066/43815388-0fe984fa-9b02-11e8-8cff-c2686f1b2448.png)

## 具体描述
视频1：44s处字幕“不等于0”，需改为“不等于1”

**Comment by DrTrippleJ** [comment]
我们检查过了，确实如此，回加上备注的

**Comment by DrTrippleJ** [comment]
已经添加备注了
