### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 【15.softmax函数】 > 编程练习中的疑问

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#443]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 > 【15.softmax函数】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/9e1364a8-e8b4-4eac-be12-4d44a139f721

## 截图
![image](https://user-images.githubusercontent.com/41724066/43815752-d78f4bd8-9b03-11e8-8fc2-fd2ed6e502e9.png)

## 具体描述
练习题答案中：result.append(i*1.0/sumExpL)，为什么要添加 i*1.0 ？
我自己编写代码时，没有这个细节，测试的时候也没有报错。
想知道这其中的区别。

**Comment by DrTrippleJ** [comment]
这里应该是为了保证浮点数吧，可能有某种计算精度的考量，亦或是把别的语言的习惯带过来了，写c++的是候不是经常会这么做吗？这个问题我就关闭了，你有疑问可以再打开
