### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 35. [Lab] 分析学生数据 > 绘制数据问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#444]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/dab588a2-51cc-4c4e-ba24-410a009943c7

## 截图
![image](https://user-images.githubusercontent.com/5260728/43816132-cea89342-9b05-11e8-80c9-dd4d5125331b.png)

## 具体描述
这里的绘制图像无法显示，我加了一行`%matplotlib inline`指令之后才正确显示了，这里应该有这么一行，否则notebook无法正常显示图像的。

**Comment by DrTrippleJ** [comment]
已修正，谢谢
