### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 【21.多类别交叉熵】 >

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#445]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 > 【21.多类别交叉熵】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/a9641a7f-f6a1-4868-9bbc-77a55f8b94be

## 截图
![image](https://user-images.githubusercontent.com/41724066/43815981-1a001244-9b05-11e8-9650-3b456149c13f.png)

## 具体描述
视频2:05处视频讲解的内容和展示的图文出现不一致（不是字幕的问题）。这一段本来要表达的意思，其实结合下前后稍微理解下就能明白。但是教程的讲述实在很绕。
其实就是，i=动物序号，j=门牌序号，Yij = 1 代表j门牌的门后出现i序号对应的动物。譬如：
Y11 =1，代表 1号门后出现鸭子，Y23=1，代表3号门后出现海狸....

**Comment by DrTrippleJ** [comment]
这里的问题我们暂时无法解决，解决后我们会close的

**Comment by ChengGoooo** [comment]
我理解 i j k 是表示第几道门。他开始用 j 来作为门的变量，但是后面又变成了 i j k 三道门

**Comment by ChengGoooo** [comment]
合并到 #417

**Comment by ChengGoooo** [comment]
合并到 #418
