### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 【21.多类别交叉熵】> 中文字幕出现漏翻译

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#448]
## 课程导航+地址
5. 神经网络 > 1. 神经网络简介 > 【21.多类别交叉熵】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/a9641a7f-f6a1-4868-9bbc-77a55f8b94be

## 截图
![image](https://user-images.githubusercontent.com/41724066/43816746-eed8948e-9b08-11e8-9b8f-70e1dbd29aa8.png)

## 具体描述
视频2：43s处开始的字幕“这个公式可行，是因为确保我们仅加上”，需改为“这个公式可行是因为，Yij要么为0要么为1，以此确保我们仅加上....”
那段关键的英文“the Y_i_j being 0 1 made sure that "没有翻译成中文字幕

**Comment by DrTrippleJ** [comment]
已修改，谢谢
