### ISSUE TITLE
5. 神经网络 > 1. 神经网络简介 > 35. [Lab] 分析学生数据 > 误差反向传播

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#449]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/dab588a2-51cc-4c4e-ba24-410a009943c7

## 截图
![image](https://user-images.githubusercontent.com/5260728/43817425-027b49b6-9b0c-11e8-8758-5d9845c9f66c.png)

## 具体描述
严格按照这里的公式写的话，损失函数不降反升，看了正确答案，写出来的公式并没有这里最开始的那个负号，去掉负号后正常了，不知道这里为什么不一致。

**Comment by DrTrippleJ** [comment]
这里我会先修改公式确保结果正确，之后会进一步排查问题，当问题确认后再关闭这个issue
