### ISSUE TITLE
5.神经网络 > 1. 神经网络简介 > 【22.Logistic 回归】>教学内容的标注有出处

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#450]
## 课程导航+地址
5.神经网络 > 1. 神经网络简介 > 【22.Logistic 回归】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/a5711d6e-abc1-41bc-a242-e8c8a9834f72

## 截图
![default](https://user-images.githubusercontent.com/41724066/43817637-0c44cb6a-9b0d-11e8-8a00-fdac5c472bd3.png)

## 具体描述
视频1:50s处视频展示的图标内容中，用红色字体表示红点的概率 P（red）=1 - P（blue）=1- 红色y
这里实际应该是  P（red）=1 - P（blue）=1- 蓝色y
同样的问题，这一章核心知识点讲的很绕。

**Comment by DrTrippleJ** [comment]
这个视频中的问题我么你现在没法解决，之后由处理办法了我们才会关闭这个issue，谢谢你的建议

**Comment by yifangwang08** [comment]
感谢反馈！视频中 P（red）=1 - P（blue）= 1- y_hat ，其中  1- y_hat 作为一个整体表示红色点的概率，所以该整体用红色标出。视频中的红色y和蓝色y所代表的的数值都是一样的。
