### ISSUE TITLE
5. 神经网络 > 2. 训练神经网络 > 3. 过拟合和欠拟合 > 字幕错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#451]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/1a0c733f-e9a5-4ffb-a905-a7a2de1975bf/concepts/207e59e5-4542-4bf3-9acf-2c67c22525e8

## 截图
![image](https://user-images.githubusercontent.com/5260728/43824521-d1d72ff0-9b24-11e8-8eb8-d84b9fc290a8.png)

## 具体描述
视频3分23秒处，“右侧的模型欠拟合”应该改成“左侧的模型欠拟合”

**Comment by DrTrippleJ** [comment]
已修改，谢谢
