### ISSUE TITLE
5. 神经网络 > 2. 训练神经网络 > 15. 已知的误差函数 > 内容问题

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#452]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/1a0c733f-e9a5-4ffb-a905-a7a2de1975bf/concepts/8d6ae663-f64d-4e91-b214-f70c2789c977

## 截图
![image](https://user-images.githubusercontent.com/5260728/43832707-e17ff642-9b3a-11e8-9457-d7a7e0668c05.png)

## 具体描述
这节视频看的让人有些懵，它的标题是“已知的误差函数”，但整个视频在介绍一些稀奇古怪命名的山，并没有给出各种误差函数的公式，我觉得这里是不是应该增加文案做些介绍呢？

**Comment by DrTrippleJ** [comment]
这一节我最开始看也有点懵逼，我们会考虑一下的并在解决后才关闭这个issue

**Comment by yifangwang08** [comment]
标题题目已改！感谢反馈！
