### ISSUE TITLE
5.神经网络 > 1. 神经网络简介 > 【22.Logistic 回归】

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#453]
## 课程导航+地址
5.神经网络 > 1. 神经网络简介 > 【22.Logistic 回归】>中文字幕翻译错误
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/a5711d6e-abc1-41bc-a242-e8c8a9834f72

## 截图
![image](https://user-images.githubusercontent.com/41724066/43834591-314ca2e6-9b41-11e8-920d-bacffeebd849.png)

## 具体描述
视频3:12s处字幕”这里yi是x（i )的标签“，需改为”这里i是x（i )的标签“或”这里i是x（i )的下角标“
说下角标，大家应该都秒懂

**Comment by DrTrippleJ** [comment]
已修改，谢谢你的建议
