### ISSUE TITLE
5. 神经网络 > 3. 通过PyTorch进行深度学习 > 2. PyTorch 简介 > 文案错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#456]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/23055792-a4f4-4ed7-aa59-3fe7516c2fcc/concepts/4b37bd60-a936-40f7-883c-1f56df8ff315

## 截图
![image](https://user-images.githubusercontent.com/5260728/43870407-ed966b22-9ba9-11e8-87f5-c134ad5e836c.png)

## 具体描述
第一自然段的“学完这节课后”连续出现了两次。

**Comment by DrTrippleJ** [comment]
已修改，谢谢
