### ISSUE TITLE
5.神经网络 > 1. 神经网络简介 >【26.[Lab] 梯度下降】>习题中更新权重的函数错误

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#458]
## 课程导航+地址
5.神经网络 > 1. 神经网络简介 >【26.[Lab] 梯度下降】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/64f025bd-1d7b-42fb-9f13-8559242c1ec9

## 截图
![image](https://user-images.githubusercontent.com/41724066/43887171-8ccd8c98-9bf0-11e8-9157-c5da57d095e4.png)

![default](https://user-images.githubusercontent.com/41724066/43888429-3b2798bc-9bf4-11e8-9fc7-198a1e201f64.png)

## 具体描述
1、梯度下降算法，更新权重的正确公式应该是：
wi +a*(y_hat - y)*xi
bi + a*(y_hat - y)

2、习题答案中，"weights -= " 和 ”bias -= "应该改为“weights +=”、“bias +=”
​

**Comment by DrTrippleJ** [comment]
@dadatangtuan 我仔细推了一遍公式，这里的公式是没有问题的~但是前面的视频里面的有问题。。。。。。。你可以再试一下，按照你说的改法应该是会出问题的
