### ISSUE TITLE
5.神经网络 > 1. 神经网络简介 >【33.反向传播】> 中文字幕错误

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#462]
## 课程导航+地址
5.神经网络 > 1. 神经网络简介 >【33.反向传播】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/4cc13714-37d7-4705-a714-314ede5290b5

## 截图
![image](https://user-images.githubusercontent.com/41724066/43957603-fb63362c-9cda-11e8-8ab4-d4878a7c1b2a.png)

## 具体描述
视频2:56s处字幕“乘以 hi相对于W11 的导数”，需改为“乘以 h1 相对于W11的导数”

**Comment by DrTrippleJ** [comment]
已修改，谢谢
