### ISSUE TITLE
Python入门 > 5. 脚本编写 >【8.在脚本中接受原始输入】> 英文字幕错误

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#464]
## 课程导航+地址
Python入门 > 5. 脚本编写 > [8.在脚本中接受原始输入](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/622bcf85-e02b-4ed1-a6b1-bc6629c8fcf7#)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/43991833-6200a85c-9da7-11e8-80c7-881cf21b3f6e.png">

## 具体描述
where  应该改为 when

**Comment by sylviasun916** [comment]
fixed and thanks!
