### ISSUE TITLE
2. Python入门 > 3. 控制流 > 4. 解决方案：条件语句：示例代码逻辑不严谨

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#468]
## 课程导航+地址
2. Python入门 > 3. 控制流 > 4. 解决方案：条件语句：示例代码逻辑不严谨（https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/8be1fc4b-a32b-4d4d-a57b-b4c6b2e34cc1）

## 截图
![image](https://user-images.githubusercontent.com/7189743/43998321-c014cd64-9e25-11e8-9120-d36ec7b0c4b0.png)

## 具体描述
题目里面已经说明，分数最大不能超过200，控制流中应该有大于200的处理，比如抛出异常之类。

**Comment by ChengGoooo** [comment]
由于这里还没有讲到更多的控制流程，所以我简单的补了一些边界判定。
