### ISSUE TITLE
2. Python入门 > 3. 控制流 > 7. 解决方案：条件布尔表达式：存在多余字符

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#470]
## 课程导航+地址
2. Python入门 > 3. 控制流 > 7. 解决方案：条件布尔表达式：存在多余字符（https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/0dc5b22c-4b87-4ce4-b23f-b35b0d5fa996）

## 截图
![image](https://user-images.githubusercontent.com/7189743/43998503-a897e5aa-9e29-11e8-8f29-2ec0642ca9f3.png)

## 具体描述
如截图红框中，句末多了一个“P”

**Comment by DrTrippleJ** [comment]
这是一个颜文字：P，吐舌头的
