### ISSUE TITLE
2. Python入门 > 3. 控制流 > 15. 练习：Break、Continue：表达意思与实际示例代码不一致

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#472]
## 课程导航+地址
2. Python入门 > 3. 控制流 > 15. 练习：Break、Continue：表达意思与实际示例代码不一致（https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/be60eb0d-24ff-4c74-b9bf-1246e1c05a50）

## 截图
![image](https://user-images.githubusercontent.com/7189743/43998701-a047b9fc-9e2e-11e8-8102-c047bd59d850.png)

## 具体描述
如截图所示，将“从中间”三个字去掉，不然下一节解决方案代码实现方式不一致。示例代码是从末尾截取最后一个新闻标题。

**Comment by DrTrippleJ** [comment]
其实感觉没问题，不过可能修改为“将最后一个新闻标题从中间截断”会更符合意思一些
