### ISSUE TITLE
2. Python入门 > 3. 控制流 > 17. Zip 和 Enumerate：视频播放完成提示跳转的时候内容异常

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#473]
## 课程导航+地址
2. Python入门 > 3. 控制流 > 17. Zip 和 Enumerate：视频播放完成提示跳转的时候内容异常（https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/a95d285d-fd94-4a29-ad95-68bf3d13b253）

## 截图
![image](https://user-images.githubusercontent.com/7189743/43998746-a5c84b5c-9e2f-11e8-81c6-9e042bc46929.png)

## 具体描述
视频播放完成提示跳转的时候内容异常

**Comment by ChengGoooo** [comment]
视频标题被某个地区的改了，现在已经改成英文了。
