### ISSUE TITLE
2. Python入门 > 4. 函数 > 7. 解决方案：变量作用域：语句不通顺

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#474]
## 课程导航+地址
2. Python入门 > 4. 函数 > 7. 解决方案：变量作用域：语句不通顺（https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/d91fa76c-cfb4-40b5-8aec-40d5b25a1e58/concepts/92cc15be-1b0d-4266-9b26-4cec6aa91f93）

## 截图
![image](https://user-images.githubusercontent.com/7189743/43998959-550d9b0e-9e34-11e8-8570-f6d5e8443c1e.png)

## 具体描述
将截图中标示的“中”字去掉

**Comment by DrTrippleJ** [comment]
变了个位置~
