### ISSUE TITLE
2. Python入门 > 5. 脚本编写 > 2. 安装 Python：进入命令提示符窗口的方式不是很明确

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#475]
## 课程导航+地址
2. Python入门 > 5. 脚本编写 > 2. 安装 Python：进入命令提示符窗口的方式不是很明确（https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/fe3a8be9-705f-4c40-9c62-4ef6a3925bd4）

## 截图
![image](https://user-images.githubusercontent.com/7189743/43999095-a80c46cc-9e37-11e8-8c49-126b946e7ba0.png)

## 具体描述
最主要的问题是如何打开运行窗口，不同的操作系统操作方式不一样，最好是能够分开举例。或者是使用快捷键，win图标键+R就可以打开运行窗口。

**Comment by DrTrippleJ** [comment]
@UdacityShuwenLiu 要不要加个括号，里面写上win+r

**Comment by UdacityShuwenLiu** [comment]
赞！加上吧，谢谢俊俊
