### ISSUE TITLE
2. Python入门 > 5. 脚本编写 > 7. 修改 Python 脚本：正确答案提交后排版错乱

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#476]
## 课程导航+地址
2. Python入门 > 5. 脚本编写 > 7. 修改 Python 脚本：正确答案提交后排版错乱（https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/e59b3000-02a4-45e0-8855-4fea925c0534）

## 截图
![image](https://user-images.githubusercontent.com/7189743/43999150-40d32e6a-9e39-11e8-8047-55653e4c9e0b.png)

## 具体描述
详见截图标示

**Comment by DrTrippleJ** [comment]
这里应该是答案完成以后把显示框压缩了，我们会反应一下的
