### ISSUE TITLE
2. Python入门 > 6. Anaconda > 1. 欢迎！：页面有一个乱码

### ISSUE THREAD

**Issue by huanghyw** [udacity/aipnd-issues-zh#477]
## 课程导航+地址
2. Python入门 > 6. Anaconda > 1. 欢迎！：页面有一个乱码（https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/356610ed-f19e-477f-9895-a52742f00d89/lessons/25688635-8bd0-4c91-b362-b84aed7926d8/concepts/4cdc5a26-1e54-4a69-8eb4-f15e37aaab7b）
## 截图
![image](https://user-images.githubusercontent.com/7189743/43999435-e43039c2-9e3e-11e8-841d-dd7c12d68e78.png)

## 具体描述
详见截图标记

**Comment by DrTrippleJ** [comment]
已修正~谢谢
