### ISSUE TITLE
5. 神经网络 > 3. 通过PyTorch进行深度学习 > 【3.PyTorch 张量】>文本内容可能有误

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#478]
## 课程导航+地址
5. 神经网络 > 3. 通过PyTorch进行深度学习 > 【3.PyTorch 张量】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/23055792-a4f4-4ed7-aa59-3fe7516c2fcc/concepts/cbab7cc5-3456-4e01-8cac-09c1d2a6b750#

## 截图
![image](https://user-images.githubusercontent.com/41724066/43999741-029f6ef4-9e45-11e8-9e26-c5d4c9069529.png)

## 具体描述
截图中红框内的文本内容，结合上下文来看，是不是应该把“三维向量”，改为“三维张量”

**Comment by DrTrippleJ** [comment]
对的，谢谢你的细心
