### ISSUE TITLE
5. 神经网络 > 3. 通过PyTorch进行深度学习 > 【5.训练网络】>出现重复段落

### ISSUE THREAD

**Issue by dadatangtuan** [udacity/aipnd-issues-zh#481]
## 课程导航+地址
5. 神经网络 > 3. 通过PyTorch进行深度学习 > 【5.训练网络】
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/23055792-a4f4-4ed7-aa59-3fe7516c2fcc/concepts/b714c17e-9eda-4f76-a59e-a05ae8318297#

## 截图
1、【反向传播】介绍中的最后一段
![image](https://user-images.githubusercontent.com/41724066/44000103-62b54f78-9e4c-11e8-8961-d04a825ef249.png)
2、【训练网络】介绍中的开头段落
![image](https://user-images.githubusercontent.com/41724066/44000116-9bf6fe44-9e4c-11e8-83e0-d5a95c23cf2b.png)

## 具体描述
截图1【反向传播】介绍中的最后一段和截图2【训练网络】介绍中的开头段落 内容完全重复，是不是仅需保留截图2中的内容。

**Comment by DrTrippleJ** [comment]
英文原文如此，我们会向美国本部那边提问的
