### ISSUE TITLE
Python入门 > 8. Lab:分类图像 >【2.Lab说明】> 链接需要翻墙

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#488]
## 课程导航+地址
Python入门 > 8. Lab:分类图像 > [2.Lab说明](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/f8c19d5d-077d-4a0d-89db-08b8fd9fbcd2/lessons/d79396c0-8fa6-4adc-ac06-9d9649fb0525/concepts/87810e5b-b946-47d9-a8e4-e9f983da3a1b)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/44036114-a1b8e386-9f43-11e8-8ee7-804acb8f447f.png">

## 具体描述
这些都是 Google 搜索链接，需要翻墙

**Comment by ChengGoooo** [comment]
其实就是 Google Images 的链接而已。

在课程的中文版，我把`https://www.google.com/search?q=`替换成了`https://www.bing.com/images/search?q=`。如果是墙内访问，会自动跳转到`https://cn.bing.com/images/search?q=`
