### ISSUE TITLE
Python入门 > 8. Lab:分类图像 >【13.将标签分类为小狗】> 视频无字幕

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#489]
## 课程导航+地址
Python入门 > 8. Lab:分类图像 > [13.将标签分类为小狗](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/f8c19d5d-077d-4a0d-89db-08b8fd9fbcd2/lessons/d79396c0-8fa6-4adc-ac06-9d9649fb0525/concepts/356e8d82-0ba2-49d4-b846-867a343764e7)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/44095198-cafb4a78-a00a-11e8-8383-a4a2f58b5912.png">

## 具体描述
视频无字幕，同样问题出现在 [14.计算结果]、[15.输出结果]

**Comment by DrTrippleJ** [comment]
ok，字幕问题我们会持续关注的

**Comment by yifangwang08** [comment]
感谢反馈！已修改！
