### ISSUE TITLE
Python入门 > 项目:控制迷宫寻宝机器人 >【1.项目介绍】> 链接不正确

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#490]
## 课程导航+地址
Python入门 > 项目:控制迷宫寻宝机器人 > [1.项目介绍](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/fe010d24-7eb5-412a-94fd-0fbd7601ddf6/modules/e059cd6a-f2f6-4eb1-8c94-4cd9a2cf96ee/lessons/468a9967-4947-4900-8455-10d8e3b1fcc3/concepts/edb13667-ea51-4d0f-acc6-ff2435146b0d)

## 截图
> 图1：
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/44096115-11b6a032-a00d-11e8-9682-379286d8aeb6.png">

## 具体描述
课程给的链接：https://github.com/udacity/AIPND-cn 是跳转到图一；
实际应该进入 P1_Robot_Controller 内，Readme 也没给出提示
[2. 项目：控制迷宫寻宝机器人] 内链接有同样问题

**Comment by ChengGoooo** [comment]
改好了
