### ISSUE TITLE
数据结果优化

### ISSUE THREAD

**Issue by nosgong** [udacity/aipnd-issues-zh#491]
## 课程导航+地址
3.Numpy,Pandas,Matplotlib >Numpy>  4.创建和保存Numpy ndarray(https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/1b5143bb-1d0f-49d7-a3c1-a87c5307260d/concepts/cf9e2370-5bc1-4ed6-9a59-9996606a8448)

## 截图
![image](https://user-images.githubusercontent.com/24370401/44129005-b4f9a968-a078-11e8-8fce-21acab813405.png)
![image](https://user-images.githubusercontent.com/24370401/44129017-cac5b00c-a078-11e8-8bfc-65f476361e6a.png)
![image](https://user-images.githubusercontent.com/24370401/44129045-e1ddb65e-a078-11e8-953a-0c87634719b2.png)
![image](https://user-images.githubusercontent.com/24370401/44129079-1e5d6a7a-a079-11e8-8e20-856b7a048d72.png)

## 具体描述
如图，多个print输出结果被合并到一行展示，建议分为多行展示

**Comment by ChengGoooo** [comment]
我这里似乎并没有这个问题，例如在 Terminal 里面运行 `.py` 文件，或者在 Sublime 里面直接 Build。

主要是我觉得插入一些空的`print()`或者插入一些`\n`，并不太利于在课程中直接阅读这些代码。

**Comment by ChengGoooo** [comment]
我先关闭了，如果有疑惑，后面再开启把
