### ISSUE TITLE
视频无字幕

### ISSUE THREAD

**Issue by nosgong** [udacity/aipnd-issues-zh#492]
## 课程导航+地址
3.Numpy, Pandas, Matplotlib > Numpy> 5.使用内置函数创建 ndarray(https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/1b5143bb-1d0f-49d7-a3c1-a87c5307260d/concepts/f99beb57-4f9a-42d9-8148-221e1828fec7)

## 截图
![image](https://user-images.githubusercontent.com/24370401/44151735-05a46cba-a0d6-11e8-965b-d1f908c16ba6.png)

## 具体描述
该小节的课程视频没有字幕

**Comment by yifangwang08** [comment]
Update! Thank you!
