### ISSUE TITLE
3.Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn> 2.课程简介 > 字幕翻译错误

### ISSUE THREAD

**Issue by nosgong** [udacity/aipnd-issues-zh#494]
## 课程导航+地址
3.Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn> 2.课程简介 > 字幕翻译错误 (https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/43855abb-dae5-46c7-9167-4b001dabd41e/concepts/1d01ba1d-a76c-4709-a833-97b5772f6ab2)

## 具体描述
视频44s处字幕It often makes sense to integrate this part of the exploration process into parts of  the data wrangling process.，其中make sense在这里应该不是翻译为‘没什么问题’，而是‘有意义’比较正确吧

**Comment by sylviasun916** [comment]
fixed and thanks
