### ISSUE TITLE
3.Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn (第二部分) > 5.小提琴图 > 视频无字幕 

### ISSUE THREAD

**Issue by nosgong** [udacity/aipnd-issues-zh#495]
## 课程导航+地址
3.Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn (第二部分) > 5.小提琴图 > 视频无字幕 (https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/0491d74e-dcd8-4700-a971-a7f1b0a26ddb/concepts/1dca3bcb-d2d4-44c2-b88e-ecea98402349)

## 截图
![image](https://user-images.githubusercontent.com/24370401/44221469-33cc1c80-a1b4-11e8-843b-e5d73dc21af8.png)

## 具体描述
第一个视频无字幕

**Comment by sylviasun916** [comment]
已有字幕，thanks
