### ISSUE TITLE
3.Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn (第二部分) > 9.调整单变量图形 > 视频缺少字幕

### ISSUE THREAD

**Issue by nosgong** [udacity/aipnd-issues-zh#496]
## 课程导航+地址
3.Numpy, Pandas, Matplotlib > Matplotlib 和 Seaborn (第二部分) > 9.调整单变量图形 > 视频无字幕 (https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/0491d74e-dcd8-4700-a971-a7f1b0a26ddb/concepts/c2627efd-b028-430f-b3f8-de1d17e9db89)

## 截图
![image](https://user-images.githubusercontent.com/24370401/44221832-514db600-a1b5-11e8-9cb1-f8eea52f3a30.png)
![image](https://user-images.githubusercontent.com/24370401/44221962-adb0d580-a1b5-11e8-8d99-ba5d8fb79475.png)

## 具体描述
视频59s处开始缺少字幕，或是偶尔几句中文字幕，且无英文对照字幕

**Comment by ChengGoooo** [comment]
@UdacityShuwenLiu 要不要改需要你来定了～

**Comment by yifangwang08** [comment]
Update! Thank you!
