### ISSUE TITLE
5. 神经网络 > 3. 通过PyTorch进行深度学习 > 7. 推理和验证 > 字幕错误

### ISSUE THREAD

**Issue by leesper** [udacity/aipnd-issues-zh#499]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/23055792-a4f4-4ed7-aa59-3fe7516c2fcc/concepts/43cb782f-2d8c-432e-94ef-cb8068f26042

## 截图
![image](https://user-images.githubusercontent.com/5260728/44272943-ba463400-a270-11e8-8195-841711ccefee.png)
![image](https://user-images.githubusercontent.com/5260728/44273122-20cb5200-a271-11e8-8ce5-77d57e13f392.png)
![image](https://user-images.githubusercontent.com/5260728/44273584-6d635d00-a272-11e8-80aa-a697591b493a.png)

## 具体描述
1. 图1，2分17秒处“functions like NormalList”应该是指“ModuleList的功能就像一般的列表一样”，这里的英文字幕直接导致中文翻译成“NormalList等函数”，有些不知所云；
2. 图2，仔细听，这里作者明显停顿了一下，因此英文字幕应该为“it just helps (停顿) helps Pytorch ...”，所以这里的house是错的
3. 图3，6分28秒处log-space居然翻译成日志空间，这里应该是对数空间

**Comment by sylviasun916** [comment]
fixed and thanks
