### ISSUE TITLE
专业词汇翻译不准确

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#501]
## 课程导航+地址
例子：AIPND >3 Numpy, Pandas, Matplotlib > 课程 4: Matplotlib 和 Seaborn（第 2 部分） > [7.集群条形图]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/0491d74e-dcd8-4700-a971-a7f1b0a26ddb/concepts/7c2f7055-36bc-4370-b81e-68a897951353

## 具体描述
1、[7.集群条形图]的lesson名称“集群条形图”应修改为：簇状柱形图
2、页面内所有集群（共9处）可酌情替换为“簇状”

**Comment by DrTrippleJ** [comment]
已修改，谢谢
