### ISSUE TITLE
字幕显示错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#502]
## 课程导航+地址
例子：AIPND >3 Numpy, Pandas, Matplotlib > 课程 4: Matplotlib 和 Seaborn（第 2 部分） > [9.调整单变量图形]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/0491d74e-dcd8-4700-a971-a7f1b0a26ddb/concepts/c2627efd-b028-430f-b3f8-de1d17e9db89#
## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
视频0:50s处字幕错误，应该删除“00:00:52, 475 -->00:00:56 067”

**Comment by sylviasun916** [comment]
字幕格式问题 已修改感谢反馈！
