### ISSUE TITLE
数学词汇翻译不准确

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#504]
## 课程导航+地址
例子：AIPND >3 Numpy, Pandas, Matplotlib > 课程 4: Matplotlib 和 Seaborn（第 2 部分） > [9.调整单变量图形]
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/0491d74e-dcd8-4700-a971-a7f1b0a26ddb/concepts/c2627efd-b028-430f-b3f8-de1d17e9db89

## 具体描述
“但是对于名目数据来说”应修改为：
“但是对于无序分类数据来说”

（分类变量分为有序分类变量和无序分类变量（又称名义分类变量），“名目数据”英文估计是“名义数据”）

**Comment by DrTrippleJ** [comment]
已添加备注，谢谢
