### ISSUE TITLE
大量字幕错误

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#505]
## 课程导航+地址
例子：AIPND > 3.numpy、pandas、matplotlib > 课程4：matplotlib、seaborn > [9. 调整单变量图形] (
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/78c9ffb7-64df-4aee-bce7-4e0c4c02fe53/modules/dd3e4af8-d576-427e-baae-925fd16ff2ff/lessons/0491d74e-dcd8-4700-a971-a7f1b0a26ddb/concepts/c2627efd-b028-430f-b3f8-de1d17e9db89)

## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
第一个视频中有大量字幕错误。

**Comment by sylviasun916** [comment]
@ChengGoooo  谷哥麻烦评估一下哦， 我看不出来具体是什么问题，谢谢。

**Comment by sylviasun916** [comment]
@ChengGoooo 谷哥从学科专业性角度麻烦评估一下哦， 我看不出来具体是什么问题，谢谢。

**Comment by ChengGoooo** [comment]
@sylviasun916 55秒之后，中英文字幕都有缺失，内容和时间轴都不对。

**Comment by sylviasun916** [comment]
@ChengGoooo 应该是美国换视频了

**Comment by sylviasun916** [comment]
已解决  感谢反馈！
