### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by ketra21** [udacity/aipnd-issues-zh#506]
## 课程导航+地址
例子：AIPND > 5.神经网络 > 课程1：神经网络简介 > [9. 感知器技巧] (https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/8ea20904-0215-4e44-afa9-bb5a720bd028)

## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
“对于这一点，有一个非常棒的技巧**虎**帮到我们。”修改为
“对于这一点，有一个非常棒的技巧**会**帮到我们。”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
