### ISSUE TITLE
神经网络 > 1. 神经网络简介 > 【10.感知器算法】 >字幕翻译错误

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#507]
## 课程导航+地址
例子：神经网络 > 1. 神经网络简介 > [10.感知器算法](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/4bfcd28a-ad62-48a0-ad9e-c346068df68e/modules/47a93218-8271-457b-aca6-e2cdca10131b/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/dc837952-c0d8-43fc-921c-f1ffe316c795)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/48784998-c5e94100-ed1e-11e8-85db-da40dab22fa9.png">

## 具体描述
视频1m38s处字幕
【如果预测为1 也就是正区域的点被错分到了负区域】，
需改为  【如果预测为1 也就是负区域的点被错分到了正区域】

**Comment by yifangwang08** [comment]
感谢反馈！已修改
