### ISSUE TITLE
Python入门 > 2. Pandas > 9. 访问 Pandas DataFrame 中的元素 > 示例的输出结果不正确

### ISSUE THREAD

**Issue by binliu-aipnd** [udacity/aipnd-issues-zh#508]
## 课程导航+地址
Python入门 > 2. Pandas > [9. 访问 Pandas DataFrame 中的元素](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/9a68756d-d8c1-4da8-a920-5e4b3109c1bc/modules/5319a970-4249-416e-93cb-0487a9ab5a5e/lessons/a961b449-db17-4967-b2e5-a62ef4493c7e/concepts/1018da7f-6b26-4b71-9e27-679dfe799e79)

## 截图
![m4_l2_9 1](https://user-images.githubusercontent.com/43527958/49416950-d08fe580-f7b6-11e8-994b-0418f720b301.JPG)

## 具体描述
将索引改为 DataFrame 中的pants列后,索引项不应该和列名同行，正确的输出应该如下图所示.

![m4_l2_9 1 fix](https://user-images.githubusercontent.com/43527958/49417076-51e77800-f7b7-11e8-9031-dd5f618e1089.JPG)

**Comment by yifangwang08** [comment]
修改好了！感谢反馈！
