### ISSUE TITLE
微积分>导数>字幕

### ISSUE THREAD

**Issue by Angelarlee** [udacity/aipnd-issues-zh#509]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/f588b255-4454-499c-a3db-30249aaefc1f/modules/ab71b739-5815-4a94-9bda-e23d7caa0ae9/lessons/d049b640-c3ee-43b5-8305-0857caac2115/concepts/bb0d7c0d-2d54-4d99-944f-28a8f95e1a79
## 截图
![image](https://user-images.githubusercontent.com/25603278/49519728-a20c2a80-f8dc-11e8-8f3b-c9347fcd9894.png)
## 具体描述
视频58s处字幕最后一个 we're，需改为were

**Comment by yifangwang08** [comment]
感谢反馈！
