### ISSUE TITLE
项目 图像分类器>workspace 使用方式

### ISSUE THREAD

**Issue by Angelarlee** [udacity/aipnd-issues-zh#510]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/11674031-eb47-4368-a724-1b1143f802a8/modules/9ec3aa45-b2bd-47ca-a513-31b21c852783/lessons/59930ed5-6f24-4cd2-bf0a-c0a0075cd7b4/concepts/62a76b66-4288-4883-9099-1c178aef9586

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/25603278/49685153-51cddc00-fb19-11e8-9656-bfa791ec6a19.png)

## 具体描述
视频的字母稍微之后一句话的样子

**Comment by Angelarlee** [comment]
具体描述：这个视频的时间轴有问题，视频字幕显示稍微滞后。

**Comment by yifangwang08** [comment]
感谢反馈！
