### ISSUE TITLE
3 python入门 - 7 面向对象编程 - 练习

### ISSUE THREAD

**Issue by WestonLu** [udacity/aipnd-issues-zh#511]
## 课程导航+地址
例子：3 python入门 > 7 面向对象编程  > [练习](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/e3d18e1a-d284-4be4-9a42-10f7f09712e5/modules/f3122cb2-9372-4cb1-9f2d-c9c54412b3a2/lessons/85771009-48c2-41c2-82de-38770d0594cb/concepts/c3c8eb3c-5af6-4b00-82c6-f188d7be8477)

## 截图

![](https://ws1.sinaimg.cn/large/006tNbRwly1fy096gzq25j31om0jedkx.jpg)

![](https://ws4.sinaimg.cn/large/006tNbRwly1fy09aemj17j31u20jmdif.jpg)

![](https://ws3.sinaimg.cn/large/006tNbRwly1fy099yo6zhj31u20jmq70.jpg)

## 具体描述

无法找到文件
shirt-exercise-zn 应该 放到第一个文件夹里面

**Comment by yifangwang08** [comment]
感谢反馈！该问题已修改，若是打开还存在问题的话可以试试 RESET DATA 哦~
