### ISSUE TITLE
3. Python入门 > 7. 面向对象编程 > 4. OOP语法：英文字幕错误

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#514]
## 课程导航+地址
例子：3. Python入门 > 7. 面向对象编程 > [4. OOP语法](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/e3d18e1a-d284-4be4-9a42-10f7f09712e5/modules/f3122cb2-9372-4cb1-9f2d-c9c54412b3a2/lessons/85771009-48c2-41c2-82de-38770d0594cb/concepts/6e899a3c-4ea6-417e-beeb-059feb2e2956)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/49694055-87c49c00-fbbd-11e8-90db-7293386eb189.png">

## 具体描述
视频23s处字幕 short，需改为 Shirt

**Comment by yifangwang08** [comment]
感谢反馈！已经修改了~
