### ISSUE TITLE
3. Python入门 > 7. 面向对象编程 > 4. OOP语法：中文翻译

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#515]
## 课程导航+地址
例子：3. Python入门 > 7. 面向对象编程 > [4. OOP语法](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/e3d18e1a-d284-4be4-9a42-10f7f09712e5/modules/f3122cb2-9372-4cb1-9f2d-c9c54412b3a2/lessons/85771009-48c2-41c2-82de-38770d0594cb/concepts/6e899a3c-4ea6-417e-beeb-059feb2e2956)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/49694211-1dadf600-fbc1-11e8-9fc3-d401e44d28ef.png">

## 具体描述
视频02m21s处字幕 第一个方法输出，改为 方法的第一个输入，可能比较通顺

**Comment by yifangwang08** [comment]
感谢反馈！已修改~
