### ISSUE TITLE
3. Python入门 > 7. 面向对象编程 > 5. 练习：OOP语法练习：文件位置错误

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#516]
## 课程导航+地址
例子：3. Python入门 > 7. 面向对象编程> [5. 练习：OOP语法练习](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/e3d18e1a-d284-4be4-9a42-10f7f09712e5/modules/f3122cb2-9372-4cb1-9f2d-c9c54412b3a2/lessons/85771009-48c2-41c2-82de-38770d0594cb/concepts/c3c8eb3c-5af6-4b00-82c6-f188d7be8477#)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/49694678-5a7deb00-fbc9-11e8-8496-7bcd704fb490.png">

## 具体描述
练习 测试代码报错，原因在于汉化的 shirt_exercise-zh.ipynb 没有放在 1.OOP_syntax_shirt_practice 文件夹内，导致找不到 tests.py 文件

**Comment by yifangwang08** [comment]
感谢反馈！问题已经修改！若打开还存在问题可以试试 RESET DATA 哦~
