### ISSUE TITLE
8. 项目：图像分类 > 项目 : 使用预训练的图像分类器识别狗的品种 > 3. 项目说明：Markdown格式

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#517]
## 课程导航+地址
例子：8. 项目：图像分类 > 项目 : 使用预训练的图像分类器识别狗的品种 > [3. 项目说明](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/11674031-eb47-4368-a724-1b1143f802a8/modules/9ec3aa45-b2bd-47ca-a513-31b21c852783/lessons/59930ed5-6f24-4cd2-bf0a-c0a0075cd7b4/concepts/7d660236-c4d5-4db6-892b-96c222195b8a)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/49698866-c762a680-fc04-11e8-8ea8-b67422534197.png">

## 具体描述
有些相同的单词，有斜体，有黑体；整体看起来比较乱，文字也没有左右对齐

**Comment by yifangwang08** [comment]
整体看起来确实有些丑...感谢反馈！已将一些不一致的地方做了修改~
