### ISSUE TITLE
4.线性代数基础--1. 简介 -3. 线性代数本质 -- 视频二阶行列式公式错误

### ISSUE THREAD

**Issue by binliu-aipnd** [udacity/aipnd-issues-zh#518]
## 课程导航+地址
4.线性代数基础--1. 简介 -3. 线性代数本质 -- [视频二阶行列式公式错误](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/b3e21058-9a6f-49b4-913d-f11e451704b7/modules/3a610571-9c9e-44aa-9e80-e37debef00f1/lessons/f5c27b42-6983-4337-bb1e-4dc897a8f8c2/concepts/ca494437-c4ce-4b28-a90b-e2236a845ff6)

## 截图
![m5_l1 3 1jpg](https://user-images.githubusercontent.com/43527958/49707109-cfeac980-fc64-11e8-9d67-208e7ec26ed1.JPG)

## 具体描述
视频30s处图像中二阶行列式计算公式等式右侧错误 ac -bc，应改为  ad - bc。

**Comment by yifangwang08** [comment]
感谢反馈！视频下方已添加备注说明~
