### ISSUE TITLE
Python入门 > 7. 面向对象编程 > 4. OOP语法：视频讲解建议

### ISSUE THREAD

**Issue by Angelarlee** [udacity/aipnd-issues-zh#521]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/e3d18e1a-d284-4be4-9a42-10f7f09712e5/modules/f3122cb2-9372-4cb1-9f2d-c9c54412b3a2/lessons/85771009-48c2-41c2-82de-38770d0594cb/concepts/6e899a3c-4ea6-417e-beeb-059feb2e2956

## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
在视频讲解过程中，鼠标标出讲解的地方，感觉用户体感会更好

**Comment by yifangwang08** [comment]
感谢反馈！我们会认真考虑你的意见的~
