### ISSUE TITLE
微积分> 2.神经网络中的微积分 > 什么是神经网络>英文字幕

### ISSUE THREAD

**Issue by Angelarlee** [udacity/aipnd-issues-zh#522]
##
微积分> 2.神经网络中的微积分 > 什么是神经网络
https://classroom.udacity.com/nanodegrees/nd089-cn/parts/f588b255-4454-499c-a3db-30249aaefc1f/modules/d1171c84-df3e-42a9-990d-144fc96566e7/lessons/186d7a04-5e09-4993-b019-b7bd98827493/concepts/f42d64a4-199f-4635-8800-1aae74134d83

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/25603278/49720845-bf097a80-fc9b-11e8-973f-95a803e76d25.png)

## 具体描述
视频2分20s处字幕和听到的语音对不上

**Comment by yifangwang08** [comment]
感谢反馈！
