### ISSUE TITLE
1. 欢迎来到…… > 课程1:欢迎…… > 4.社区指南：链接

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#533]
## 课程导航+地址
例子：1. 欢迎来到…… > 课程1:欢迎…… > [4.社区指南](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/6877e0e5-cc6e-484c-9a65-5a785d22893e/modules/9ef0592d-aab4-4065-8b4b-751a942277fc/lessons/4048d6c9-b55d-4003-97c5-c4014113313f/concepts/80713f62-0300-4c5a-b630-35babe33f266)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/50006525-fef89680-ffe8-11e8-9b2a-6379f58f852a.png">

## 具体描述
视频44s处字幕XXXX，需改为XXXX红框链接均指向 Udacity 英文网址，是否有对应中文网址

**Comment by yifangwang08** [comment]
感谢反馈！
