### ISSUE TITLE
2. Python 零基础热身课 > 1.Turtle 和代码 > 19.列表和循环：翻译错误

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#534]
## 课程导航+地址
例子：2. Python 零基础热身课 > 1.Turtle 和代码 > [19.列表和循环](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/72132488-1426-4ec3-8a17-a8be840060b0/modules/e35b4198-e4b0-4c16-bd13-cd78723b7d6d/lessons/1547d570-d579-43bd-bdcb-fc911e555320/concepts/402392ea-aa5e-4549-9243-95350d5b9ce8)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/50011488-35d5a900-fff7-11e8-8c09-16ed56c4cf08.png">

## 具体描述
视频02m19s处字幕 先前移动，需改为 向前移动

**Comment by yifangwang08** [comment]
感谢反馈！
