### ISSUE TITLE
3. Python入门 > 课程3：控制流 > 8.Practice：For loop：课程内容未汉化

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#535]
## 课程导航+地址
例子：3. Python入门 > 课程3：控制流 > [8.Practice：For loop](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/e3d18e1a-d284-4be4-9a42-10f7f09712e5/modules/d49d181a-c0e9-46d7-a79f-773250390e34/lessons/6c17ece8-b506-4314-9f60-276611d0e5c7/concepts/69128dbd-66d0-42bc-902a-28739a45c349)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/50094034-28196100-024d-11e9-81b6-cd665748812c.png">

## 具体描述
课程小节内容未汉化，第 8、9、13节

**Comment by yifangwang08** [comment]
感谢反馈！
