### ISSUE TITLE
3. Python入门 > 课程3：控制流 > 19.Zip 和 Enumerate：文字错误

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#536]
## 课程导航+地址
例子：3. Python入门 > 课程3：控制流 > [19.Zip 和 Enumerate](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/e3d18e1a-d284-4be4-9a42-10f7f09712e5/modules/d49d181a-c0e9-46d7-a79f-773250390e34/lessons/6c17ece8-b506-4314-9f60-276611d0e5c7/concepts/a95d285d-fd94-4a29-ad95-68bf3d13b253)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/50096593-0c18be00-0253-11e9-9306-942fab5e8ba3.png">

## 具体描述
"拆封列表"， 需改为 "拆分列表"

**Comment by yifangwang08** [comment]
感谢反馈！
