### ISSUE TITLE
5. 神经网络 > 2. 训练神经网络 > 7. Dropout > 字幕翻译错误

### ISSUE THREAD

**Issue by binliu-aipnd** [udacity/aipnd-issues-zh#537]
## 课程导航+地址
5. 神经网络 > 2. 训练神经网络 > 7. Dropout > [字幕翻译错误](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/370d9272-8da5-4776-9306-3b465572c87b/modules/299dafc1-3ac7-4163-ab74-398a53da4dd5/lessons/1a0c733f-e9a5-4ffb-a905-a7a2de1975bf/concepts/05d1b01f-191e-4b45-8e93-469aa0e05877)

## 截图
![m7_l7 1](https://user-images.githubusercontent.com/43527958/50158953-688de300-0310-11e9-9dbc-0343a0a54cf9.JPG)

## 具体描述
视频60s处字幕“篮球”，需改为“棒球”

**Comment by yifangwang08** [comment]
感谢反馈！
