### ISSUE TITLE
3. Python入门 > 课程5：脚本编写 > 4.[For Windows] Configuring…：课程内容未翻译

### ISSUE THREAD

**Issue by CallMeLog** [udacity/aipnd-issues-zh#539]
## 课程导航+地址
例子：3. Python入门 > 课程5：脚本编写 > [4.[For Windows] Configuring…](https://classroom.udacity.com/nanodegrees/nd089-cn/parts/e3d18e1a-d284-4be4-9a42-10f7f09712e5/modules/d49d181a-c0e9-46d7-a79f-773250390e34/lessons/54b2e14f-d669-45ba-9299-f8e4ab4ad5b7/concepts/3a55412c-06b5-4422-8b77-5078f9cb32da)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/50293833-75950880-04af-11e9-9edb-b0f083b18794.png">

## 具体描述
课程内容未翻译，同样的还有第15、16小节

**Comment by yifangwang08** [comment]
感谢反馈！
